### ISSUE TITLE
Access to file '/usr/share/netdata/web/' is not permitted

### ISSUE THREAD

**Issue by aapis** [firehol/netdata#1209]
I've gone through all the threads with this issue and I think this is a different issue.  Dashboard URL throws the error in the title, so I checked `http://dashboard:19999/netdata.conf` to see what was being loaded.  `run as user`, `web files owner` and `web files group` are empty in this version of the config, but they are populated in `/etc/netdata/netdata.conf`.

```shell
# http://server:1999/netdata.conf
[global]
        ...
	# pthread stack size = 8388608
	# run as user = 
	# web files owner = 
	# web files group = 
```

```shell
# /etc/netdata/netdata.conf
[global]
        ...
	# pthread stack size = 8388608
	# run as user = netdata
	# web files owner = netdata
	# web files group = netdata
```

This was working only a few minutes ago, the only thing I did was attempt to get MySQL monitoring working so I did restart the service.  Permissions appear to be ok.

```shell
$ ls -lA /usr/share/netdata
total 4
drwxr-xr-x 8 netdata netdata 4096 Oct 27 10:42 web
```

```shell
$ ls -lA /usr/share/netdata/web/
total 724
drwxr-xr-x 2 netdata netdata   4096 Oct 27 10:42 css
-rw-r--r-- 1 netdata netdata  10689 Oct 27 10:42 dashboard.css
-rw-r--r-- 1 netdata netdata  22030 Oct 27 10:42 dashboard.html
-rw-r--r-- 1 netdata netdata  37954 Oct 27 10:42 dashboard_info.js
-rw-r--r-- 1 netdata netdata 262596 Oct 27 10:42 dashboard.js
-rw-r--r-- 1 netdata netdata  10912 Oct 27 10:42 dashboard.slate.css
-rw-r--r-- 1 netdata netdata   6838 Oct 27 10:42 demo2.html
-rw-r--r-- 1 netdata netdata   2047 Oct 27 10:42 demo.html
-rw-r--r-- 1 netdata netdata  44319 Oct 27 10:42 demosites.html
-rw-r--r-- 1 netdata netdata  56875 Oct 27 10:42 favicon.ico
drwxr-xr-x 2 netdata netdata   4096 Oct 27 10:42 fonts
-rw-r--r-- 1 netdata netdata   8128 Oct 27 10:42 goto-host-from-alarm.html
drwxr-xr-x 2 netdata netdata   4096 Oct 27 10:42 images
-rw-r--r-- 1 netdata netdata 152576 Oct 27 10:42 index.html
drwxr-xr-x 2 netdata netdata   4096 Oct 27 10:42 lib
-rw-r--r-- 1 netdata netdata  28889 Oct 27 10:42 netdata-swagger.json
-rw-r--r-- 1 netdata netdata  17956 Oct 27 10:42 netdata-swagger.yaml
drwxr-xr-x 2 netdata netdata   4096 Oct 27 10:42 old
-rw-r--r-- 1 netdata netdata   7727 Oct 27 10:42 registry.html
-rw-r--r-- 1 netdata netdata     26 Oct 27 10:42 robots.txt
-rw-r--r-- 1 netdata netdata  10398 Oct 27 10:42 tv.html
-rw-r--r-- 1 netdata netdata     41 Oct 27 10:42 version.txt
drwxr-xr-x 3 netdata netdata   4096 Oct 27 10:42 .well-known
```

**Comment by ktsaou** [comment]
how did you run netdata?
can you post: `ps fax | grep netdata` ?

**Comment by aapis** [comment]
To restart I do `killall netdata && sleep 10 && /usr/sbin/netdata`.  Server is Ubuntu 14.04, netdata 1.4.0.

```shell
$ ps fax | grep netdata
28141 pts/6    S+     0:00              \_ grep --color=auto netdata
23762 ?        Sl     0:03 /usr/sbin/netdata
23765 ?        S      0:01  \_ bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
23776 ?        S      0:07  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
23778 ?        Sl     0:02  \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
```

**Comment by ktsaou** [comment]
Do you have user `netdata` on your system?

Please run:

```sh
getent passwd netdata
```

what does it say?

Can you switch to user netdata? Please run:

```sh
su -s /bin/bash netdata
```

Does it work?

Is there an error logged in `/var/log/netdata/error.log`?

**Comment by aapis** [comment]
```shell
$ getent passwd netdata
netdata:x:999:999:netdata:/:/usr/sbin/nologin
```

```shell
$ su -s /bin/bash netdata
```

This prompts for a password.

Last few lines of `/var/log/netdata/error.log`

```
2016-11-04 11:22:14: python.d INFO: Disabled mysql/socket3_root
2016-11-04 11:22:14: netdata: ERROR: File /var/cache/netdata/apache_local.connections/main.db is too old. Clearing it.
2016-11-04 11:22:14: netdata: ERROR: File /var/cache/netdata/apache_local.conns_async/main.db is too old. Clearing it.
2016-11-04 11:27:40: netdata: ERROR: Received signal 15. Exiting...
2016-11-04 11:27:40: netdata: INFO: Saving database...
2016-11-04 11:27:40: netdata: INFO: CGROUP thread exiting
2016-11-04 11:27:41: netdata: INFO: PROC thread exiting
2016-11-04 11:27:41: netdata: INFO: PLUGINSD: '/usr/libexec/netdata/plugins.d/python.d.plugin' on pid 18970 stopped after 3912 successful data collections (ENDs).
2016-11-04 11:27:41: Prevented 4 log messages from displaying
2016-11-04 11:27:41: netdata: INFO: PLUGINSD: '/usr/libexec/netdata/plugins.d/apps.plugin' on pid 18966 stopped after 17004 successful data collections (ENDs).
2016-11-04 11:27:41: netdata: ERROR: child pid 18960 killed by signal 13. (errno 9, Bad file descriptor)
2016-11-04 11:27:41: netdata: INFO: NetData exiting. Bye bye...
Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 533, in <module>
    run()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 528, in run
    charts.update()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 409, in update
    msg.fatal("no more jobs")
  File "/usr/libexec/netdata/python.d/python_modules/msg.py", line 72, in fatal
    print('DISABLE')
IOError: [Errno 32] Broken pipe
```

**Comment by ktsaou** [comment]
I think you are starting netdata as a user, not root.
Netdata cannot switch to another user if not started as root.

**Comment by aapis** [comment]
Ah, so simple!  Thanks Costas, and thanks again for the awesome support on my (many) questions!

The following worked for me.  It was the sudo on `/usr/sbin/netdata` that I was missing when restarting the service.

```shell
sudo killall netdata && sudo /usr/sbin/netdata
```
