### ISSUE TITLE
Question - How do I use this with Apache2?

### ISSUE THREAD

**Issue by grahamcupr** [firehol/netdata#1298]
This is not a bug at all, it's just my lack of knowledge of the application, as I've only been using it for a few days.

I'm probably being stupid here. but I can't figure out how to add the apache plugin to the user interface. I've got a netdata installation on the same server as an Apache installation, and while everything else is working amazingly well, I just can't figure out how to get Apache stats to appear on the page too, even after reading the documentation. Any help would be great.

Netdata is an awesome piece of open-source software, one of the best projects I've used, and certainly the best network monitor I've ever used.

Thanks

**Comment by ktsaou** [comment]
Thanks!

netdata is trying to fetch these URLs: https://github.com/firehol/netdata/blob/322d10a2252d1652b3137c1abacc8a355697e1f9/conf.d/python.d/apache.conf#L70-L80

any of them will do. If your apache is listening at a different URL for mod-status, add your URL too. However, in most of the cases where this does not work out of the box, mod-status is simply disabled in apache.

**Comment by ktsaou** [comment]
You can check this by hand, on the terminal:

```sh
curl 'http://localhost/server-status?auto'
```

**Comment by grahamcupr** [comment]
Thanks for the quick response. I'm getting 404 not found, which I don't understand, because I'm definitely running Apache2 on that box.

**Comment by l2isbad** [comment]
To access server-status you need to define location

example: access from localhost only
        <Location "/server-status">
            SetHandler server-status
            Require ip 127.0.0.1
        </Location>

**Comment by grahamcupr** [comment]
Ah, right, I'll give that a go and get back to you.

**Comment by grahamcupr** [comment]
Hi again,

I'm a newbie to Apache, and I've tried adding the above to the apache2.conf, but it's still not picking up. I've also added a LoadModule line to the config file to load the mod_status module but still nothing's happening.

**Comment by grahamcupr** [comment]
Right. I discovered that I had lightttpd running on the server, which was blocking apache. I must have installed lighttpd ages ago and forgot about it. Anyway, I executed the curl command above and now am getting the correct response. What do I need to do now, just reboot the machine and netdata will pick up the apache settings?

**Comment by ktsaou** [comment]
just restart netdata: `service netdata restart`

**Comment by grahamcupr** [comment]
Hi there, I must be missing something else, I've done the above and I still can't see any Apache details or graphs. This was the output of "curl 'http://localhost/server-status?auto;" was

Total Accesses: 1
Total kBytes: 0
CPULoad: .0300679
Uptime: 1031
ReqPerSec: .000969932
BytesPerSec: 0
BytesPerReq: 0
BusyWorkers: 1
IdleWorkers: 49
ConnsTotal: 0
ConnsAsyncWriting: 0
ConnsAsyncKeepAlive: 0
ConnsAsyncClosing: 0
Scoreboard: _________________________________W________________

Does this look correct?

**Comment by ktsaou** [comment]
You have to restart netdata and refresh the dashboard (hit F5 on your browser).
Also, please access something on your apache server. Netdata has an auto-detection feature that does not add charts without any useful info.

**Comment by grahamcupr** [comment]
Unfortunately that didn't work. Apache appears to be listening via IPV6 though, if that makes any difference? I set up an example html file in the root of the default virtual app that apache installs, refreshed the page a few times. In the server-status print out I can see that bytes have been transferred, but no change in Netdata. I restarted the service and browser as you suggested too.

**Comment by ktsaou** [comment]
Could you please run:

```sh
/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 apache
```

and post here the output?

**Comment by grahamcupr** [comment]
$ /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 apache
2016-11-30 22:29:20:  INFO: Using python v2
2016-11-30 22:29:21: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2016-11-30 22:29:21: python.d ERROR: /etc/netdata/python.d.conf is not a valid configuration file
2016-11-30 22:29:21: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['apache']
2016-11-30 22:29:21: python.d DEBUG: apache: loading module configuration: '/etc/netdata/python.d/apache.conf'2016-11-30 22:29:21: python.d ERROR: /etc/netdata/python.d/apache.conf is not a valid configuration file
2016-11-30 22:29:21: python.d DEBUG: apache: reading configuration
2016-11-30 22:29:21: python.d DEBUG: apache: job added
2016-11-30 22:29:21: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2016-11-30 22:29:21: python.d INFO: CHECKED OK: apache_local
2016-11-30 22:29:21: python.d DEBUG: overridden job names: []
2016-11-30 22:29:21: python.d DEBUG: all remaining job objects: [<Service(local, initial daemon)>]CHART apache_local.requests '' 'apache Requests' requests/s requests apache.requests line 60000 1
DIMENSION requests requests incremental 1 1
CHART apache_local.connections '' 'apache Connections' connections connections apache.connections line 60001 1DIMENSION connections connections absolute 1 1
CHART apache_local.conns_async '' 'apache Async Connections' connections connections apache.conns_async stacked 60002 1
DIMENSION keepalive keepalive absolute 1 1
DIMENSION closing closing absolute 1 1
DIMENSION writing writing absolute 1 1
CHART apache_local.net '' 'apache Bandwidth' kilobytes/s bandwidth apache.net area 60003 1
DIMENSION sent sent incremental 1 1
CHART apache_local.workers '' 'apache Workers' workers workers apache.workers stacked 60004 1
DIMENSION idle idle absolute 1 1
DIMENSION busy busy absolute 1 1
CHART apache_local.reqpersec '' 'apache Lifetime Avg. Requests/s' requests/s statistics apache.reqpersec area 60005 1
DIMENSION requests_sec requests_sec absolute 1 1
CHART apache_local.bytespersec '' 'apache Lifetime Avg. Bandwidth/s' kilobytes/s statistics apache.bytesperreq area 60006 1
DIMENSION size_sec size_sec absolute 1 1000
CHART apache_local.bytesperreq '' 'apache Lifetime Avg. Response Size' bytes/request statistics apache.bytesperreq area 60007 1
DIMENSION size_req size_req absolute 1 1

CHART netdata.plugin_pythond_apache_local '' 'Execution time for apache_local plugin' 'milliseconds / run' python.d netdata.plugin_python area 145000 1
DIMENSION run_time 'run time' absolute 1 1

2016-11-30 22:29:21: python.d DEBUG: created charts for apache_local
2016-11-30 22:29:21: python.d DEBUG: apache_local starting data collection - update frequency: 1.0  retries allowed: 60
2016-11-30 22:29:21: python.d DEBUG: apache_local sleeping for 0.564632892609 secs to reach frequency of 1.0 secs, now: 1480544961.44  next: 1480544962.0  penalty: 0BEGIN apache_local.requests 0
SET requests = 185
END
BEGIN apache_local.connections 0
SET connections = 0
END
BEGIN apache_local.conns_async 0
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 0
SET sent = 3383
END
BEGIN apache_local.workers 0
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 0
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 0
SET size_sec = 357
END
BEGIN apache_local.bytesperreq 0
SET size_req = 18725
END

BEGIN netdata.plugin_pythond_apache_local 0
SET run_time = 10
END

2016-11-30 22:29:22: python.d DEBUG: apache_local apache_local updated in 10 ms
2016-11-30 22:29:22: python.d DEBUG: apache_local sleeping for 0.987874984741 secs to reach frequency of 1.0 secs, now: 1480544962.01  next: 1480544963.0  penalty: 0BEGIN apache_local.requests 1000479
SET requests = 186
END
BEGIN apache_local.connections 1000479
SET connections = 0
END
BEGIN apache_local.conns_async 1000479
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000479
SET sent = 3384
END
BEGIN apache_local.workers 1000479
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000479
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000479
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1000479
SET size_req = 18630
END

BEGIN netdata.plugin_pythond_apache_local 1000479
SET run_time = 8
END

2016-11-30 22:29:23: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:23: python.d DEBUG: apache_local sleeping for 0.989594936371 secs to reach frequency of 1.0 secs, now: 1480544963.01  next: 1480544964.0  penalty: 0BEGIN apache_local.requests 1000017
SET requests = 187
END
BEGIN apache_local.connections 1000017
SET connections = 0
END
BEGIN apache_local.conns_async 1000017
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000017
SET sent = 3384
END
BEGIN apache_local.workers 1000017
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000017
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000017
SET size_sec = 357
END
BEGIN apache_local.bytesperreq 1000017
SET size_req = 18530
END

BEGIN netdata.plugin_pythond_apache_local 1000017
SET run_time = 8
END

2016-11-30 22:29:24: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:24: python.d DEBUG: apache_local sleeping for 0.98973107338 secs to reach frequency of 1.0 secs, now: 1480544964.01  next: 1480544965.0  penalty: 0
BEGIN apache_local.requests 999941
SET requests = 188
END
BEGIN apache_local.connections 999941
SET connections = 0
END
BEGIN apache_local.conns_async 999941
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 999941
SET sent = 3385
END
BEGIN apache_local.workers 999941
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 999941
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 999941
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 999941
SET size_req = 18437
END

BEGIN netdata.plugin_pythond_apache_local 999941
SET run_time = 4
END

2016-11-30 22:29:25: python.d DEBUG: apache_local apache_local updated in 4 ms
2016-11-30 22:29:25: python.d DEBUG: apache_local sleeping for 0.993777990341 secs to reach frequency of 1.0 secs, now: 1480544965.01  next: 1480544966.0  penalty: 0BEGIN apache_local.requests 999919
SET requests = 189
END
BEGIN apache_local.connections 999919
SET connections = 0
END
BEGIN apache_local.conns_async 999919
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 999919
SET sent = 3386
END
BEGIN apache_local.workers 999919
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 999919
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 999919
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 999919
SET size_req = 18345
END

BEGIN netdata.plugin_pythond_apache_local 999919
SET run_time = 8
END

2016-11-30 22:29:26: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:26: python.d DEBUG: apache_local sleeping for 0.990077972412 secs to reach frequency of 1.0 secs, now: 1480544966.01  next: 1480544967.0  penalty: 0BEGIN apache_local.requests 1000205
SET requests = 190
END
BEGIN apache_local.connections 1000205
SET connections = 0
END
BEGIN apache_local.conns_async 1000205
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000205
SET sent = 3387
END
BEGIN apache_local.workers 1000205
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000205
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000205
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1000205
SET size_req = 18254
END

BEGIN netdata.plugin_pythond_apache_local 1000205
SET run_time = 8
END

2016-11-30 22:29:27: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:27: python.d DEBUG: apache_local sleeping for 0.990082025528 secs to reach frequency of 1.0 secs, now: 1480544967.01  next: 1480544968.0  penalty: 0BEGIN apache_local.requests 999910
SET requests = 191
END
BEGIN apache_local.connections 999910
SET connections = 0
END
BEGIN apache_local.conns_async 999910
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 999910
SET sent = 3387
END
BEGIN apache_local.workers 999910
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 999910
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 999910
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 999910
SET size_req = 18158
END

BEGIN netdata.plugin_pythond_apache_local 999910
SET run_time = 8
END

2016-11-30 22:29:28: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:28: python.d DEBUG: apache_local sleeping for 0.989985942841 secs to reach frequency of 1.0 secs, now: 1480544968.01  next: 1480544969.0  penalty: 0BEGIN apache_local.requests 1000015
SET requests = 192
END
BEGIN apache_local.connections 1000015
SET connections = 0
END
BEGIN apache_local.conns_async 1000015
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000015
SET sent = 3388
END
BEGIN apache_local.workers 1000015
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000015
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000015
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1000015
SET size_req = 18069
END

BEGIN netdata.plugin_pythond_apache_local 1000015
SET run_time = 8
END

2016-11-30 22:29:29: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:29: python.d DEBUG: apache_local sleeping for 0.98978805542 secs to reach frequency of 1.0 secs, now: 1480544969.01  next: 1480544970.0  penalty: 0
BEGIN apache_local.requests 999913
SET requests = 193
END
BEGIN apache_local.connections 999913
SET connections = 0
END
BEGIN apache_local.conns_async 999913
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 999913
SET sent = 3389
END
BEGIN apache_local.workers 999913
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 999913
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 999913
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 999913
SET size_req = 17981
END

BEGIN netdata.plugin_pythond_apache_local 999913
SET run_time = 7
END

2016-11-30 22:29:30: python.d DEBUG: apache_local apache_local updated in 7 ms
2016-11-30 22:29:30: python.d DEBUG: apache_local sleeping for 0.990940093994 secs to reach frequency of 1.0 secs, now: 1480544970.01  next: 1480544971.0  penalty: 0BEGIN apache_local.requests 1000000
SET requests = 194
END
BEGIN apache_local.connections 1000000
SET connections = 0
END
BEGIN apache_local.conns_async 1000000
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000000
SET sent = 3390
END
BEGIN apache_local.workers 1000000
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000000
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000000
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1000000
SET size_req = 17893
END

BEGIN netdata.plugin_pythond_apache_local 1000000
SET run_time = 8
END

2016-11-30 22:29:31: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:31: python.d DEBUG: apache_local sleeping for 0.989905118942 secs to reach frequency of 1.0 secs, now: 1480544971.01  next: 1480544972.0  penalty: 0BEGIN apache_local.requests 1000087
SET requests = 195
END
BEGIN apache_local.connections 1000087
SET connections = 0
END
BEGIN apache_local.conns_async 1000087
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000087
SET sent = 3390
END
BEGIN apache_local.workers 1000087
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000087
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000087
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1000087
SET size_req = 17801
END

BEGIN netdata.plugin_pythond_apache_local 1000087
SET run_time = 8
END

2016-11-30 22:29:32: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:32: python.d DEBUG: apache_local sleeping for 0.990106105804 secs to reach frequency of 1.0 secs, now: 1480544972.01  next: 1480544973.0  penalty: 0BEGIN apache_local.requests 1000068
SET requests = 196
END
BEGIN apache_local.connections 1000068
SET connections = 0
END
BEGIN apache_local.conns_async 1000068
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000068
SET sent = 3391
END
BEGIN apache_local.workers 1000068
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000068
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000068
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1000068
SET size_req = 17716
END

BEGIN netdata.plugin_pythond_apache_local 1000068
SET run_time = 8
END

2016-11-30 22:29:33: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:33: python.d DEBUG: apache_local sleeping for 0.990127086639 secs to reach frequency of 1.0 secs, now: 1480544973.01  next: 1480544974.0  penalty: 0BEGIN apache_local.requests 999889
SET requests = 197
END
BEGIN apache_local.connections 999889
SET connections = 0
END
BEGIN apache_local.conns_async 999889
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 999889
SET sent = 3392
END
BEGIN apache_local.workers 999889
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 999889
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 999889
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 999889
SET size_req = 17631
END

BEGIN netdata.plugin_pythond_apache_local 999889
SET run_time = 4
END

2016-11-30 22:29:34: python.d DEBUG: apache_local apache_local updated in 4 ms
2016-11-30 22:29:34: python.d DEBUG: apache_local sleeping for 0.994429111481 secs to reach frequency of 1.0 secs, now: 1480544974.01  next: 1480544975.0  penalty: 0BEGIN apache_local.requests 999886
SET requests = 198
END
BEGIN apache_local.connections 999886
SET connections = 0
END
BEGIN apache_local.conns_async 999886
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 999886
SET sent = 3392
END
BEGIN apache_local.workers 999886
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 999886
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 999886
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 999886
SET size_req = 17542
END

BEGIN netdata.plugin_pythond_apache_local 999886
SET run_time = 7
END

2016-11-30 22:29:35: python.d DEBUG: apache_local apache_local updated in 7 ms
2016-11-30 22:29:35: python.d DEBUG: apache_local sleeping for 0.990511894226 secs to reach frequency of 1.0 secs, now: 1480544975.01  next: 1480544976.0  penalty: 0BEGIN apache_local.requests 1000164
SET requests = 199
END
BEGIN apache_local.connections 1000164
SET connections = 0
END
BEGIN apache_local.conns_async 1000164
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000164
SET sent = 3393
END
BEGIN apache_local.workers 1000164
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000164
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000164
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1000164
SET size_req = 17459
END

BEGIN netdata.plugin_pythond_apache_local 1000164
SET run_time = 8
END

2016-11-30 22:29:36: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:36: python.d DEBUG: apache_local sleeping for 0.99013710022 secs to reach frequency of 1.0 secs, now: 1480544976.01  next: 1480544977.0  penalty: 0
BEGIN apache_local.requests 999987
SET requests = 200
END
BEGIN apache_local.connections 999987
SET connections = 0
END
BEGIN apache_local.conns_async 999987
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 999987
SET sent = 3394
END
BEGIN apache_local.workers 999987
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 999987
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 999987
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 999987
SET size_req = 17377
END

BEGIN netdata.plugin_pythond_apache_local 999987
SET run_time = 8
END

2016-11-30 22:29:37: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:37: python.d DEBUG: apache_local sleeping for 0.989962100983 secs to reach frequency of 1.0 secs, now: 1480544977.01  next: 1480544978.0  penalty: 0BEGIN apache_local.requests 999916
SET requests = 201
END
BEGIN apache_local.connections 999916
SET connections = 0
END
BEGIN apache_local.conns_async 999916
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 999916
SET sent = 3395
END
BEGIN apache_local.workers 999916
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 999916
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 999916
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 999916
SET size_req = 17295
END

BEGIN netdata.plugin_pythond_apache_local 999916
SET run_time = 8
END

2016-11-30 22:29:38: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:38: python.d DEBUG: apache_local sleeping for 0.989233970642 secs to reach frequency of 1.0 secs, now: 1480544978.01  next: 1480544979.0  penalty: 0BEGIN apache_local.requests 1000313
SET requests = 202
END
BEGIN apache_local.connections 1000313
SET connections = 0
END
BEGIN apache_local.conns_async 1000313
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000313
SET sent = 3395
END
BEGIN apache_local.workers 1000313
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000313
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000313
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1000313
SET size_req = 17210
END

BEGIN netdata.plugin_pythond_apache_local 1000313
SET run_time = 4
END

2016-11-30 22:29:39: python.d DEBUG: apache_local apache_local updated in 4 ms
2016-11-30 22:29:39: python.d DEBUG: apache_local sleeping for 0.993937015533 secs to reach frequency of 1.0 secs, now: 1480544979.01  next: 1480544980.0  penalty: 0BEGIN apache_local.requests 1003901
SET requests = 203
END
BEGIN apache_local.connections 1003901
SET connections = 0
END
BEGIN apache_local.conns_async 1003901
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1003901
SET sent = 3396
END
BEGIN apache_local.workers 1003901
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1003901
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1003901
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1003901
SET size_req = 17130
END

BEGIN netdata.plugin_pythond_apache_local 1003901
SET run_time = 7
END

2016-11-30 22:29:40: python.d DEBUG: apache_local apache_local updated in 7 ms
2016-11-30 22:29:40: python.d DEBUG: apache_local sleeping for 0.986944913864 secs to reach frequency of 1.0 secs, now: 1480544980.01  next: 1480544981.0  penalty: 0BEGIN apache_local.requests 995782
SET requests = 204
END
BEGIN apache_local.connections 995782
SET connections = 0
END
BEGIN apache_local.conns_async 995782
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 995782
SET sent = 3397
END
BEGIN apache_local.workers 995782
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 995782
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 995782
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 995782
SET size_req = 17051
END

BEGIN netdata.plugin_pythond_apache_local 995782
SET run_time = 8
END

2016-11-30 22:29:41: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:41: python.d DEBUG: apache_local sleeping for 0.98977804184 secs to reach frequency of 1.0 secs, now: 1480544981.01  next: 1480544982.0  penalty: 0
BEGIN apache_local.requests 1000092
SET requests = 205
END
BEGIN apache_local.connections 1000092
SET connections = 0
END
BEGIN apache_local.conns_async 1000092
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000092
SET sent = 3397
END
BEGIN apache_local.workers 1000092
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000092
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000092
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1000092
SET size_req = 16968
END

BEGIN netdata.plugin_pythond_apache_local 1000092
SET run_time = 8
END

2016-11-30 22:29:42: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:42: python.d DEBUG: apache_local sleeping for 0.98942899704 secs to reach frequency of 1.0 secs, now: 1480544982.01  next: 1480544983.0  penalty: 0
BEGIN apache_local.requests 999994
SET requests = 206
END
BEGIN apache_local.connections 999994
SET connections = 0
END
BEGIN apache_local.conns_async 999994
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 999994
SET sent = 3398
END
BEGIN apache_local.workers 999994
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 999994
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 999994
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 999994
SET size_req = 16891
END

BEGIN netdata.plugin_pythond_apache_local 999994
SET run_time = 8
END

2016-11-30 22:29:43: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:43: python.d DEBUG: apache_local sleeping for 0.98983001709 secs to reach frequency of 1.0 secs, now: 1480544983.01  next: 1480544984.0  penalty: 0
BEGIN apache_local.requests 1000017
SET requests = 207
END
BEGIN apache_local.connections 1000017
SET connections = 0
END
BEGIN apache_local.conns_async 1000017
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 1000017
SET sent = 3399
END
BEGIN apache_local.workers 1000017
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 1000017
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 1000017
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 1000017
SET size_req = 16814
END

BEGIN netdata.plugin_pythond_apache_local 1000017
SET run_time = 8
END

2016-11-30 22:29:44: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:44: python.d DEBUG: apache_local sleeping for 0.989919900894 secs to reach frequency of 1.0 secs, now: 1480544984.01  next: 1480544985.0  penalty: 0BEGIN apache_local.requests 999989
SET requests = 208
END
BEGIN apache_local.connections 999989
SET connections = 0
END
BEGIN apache_local.conns_async 999989
SET keepalive = 0
SET closing = 0
SET writing = 0
END
BEGIN apache_local.net 999989
SET sent = 3400
END
BEGIN apache_local.workers 999989
SET idle = 49
SET busy = 1
END
BEGIN apache_local.reqpersec 999989
SET requests_sec = 0
END
BEGIN apache_local.bytespersec 999989
SET size_sec = 358
END
BEGIN apache_local.bytesperreq 999989
SET size_req = 16738
END

BEGIN netdata.plugin_pythond_apache_local 999989
SET run_time = 8
END

2016-11-30 22:29:45: python.d DEBUG: apache_local apache_local updated in 8 ms
2016-11-30 22:29:45: python.d DEBUG: apache_local sleeping for 0.989589929581 secs to reach frequency of 1.0 secs, now: 1480544985.01  next: 1480544986.0  penalty: 0^CTraceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 549, in <module>
    run()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 544, in run
    charts.update()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 411, in update
    time.sleep(1)
KeyboardInterrup

**Comment by ktsaou** [comment]
It works then. The charts should there.

**Comment by grahamcupr** [comment]
I did notice at the top of the printout above that there was a couple of conf errors along the lines of 'python.conf is not a valid configuration file'

**Comment by grahamcupr** [comment]
I've just got it working! 

In the end I had a couple of problems. I had conflicting web server software on the machine, and I guess I'd messed up a couple of configuration files. I just ran the netdata updater, to sort out the messed up files and now it's working.

Thanks for all you help, and keep up the great work on netdata!
