### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by jtrip** [firehol/netdata#1635]
Is Python3 actually supported? The installer script recognizes it so I was thinking it might be.
On Debian 8,  apt-get (from script or manual suggestion) fails.
```
Setting up python-yaml (3.11-2) ...                                                                                    
Traceback (most recent call last):                                                                                     
  File "/usr/bin/pycompile", line 35, in <module>                                                                      
    from debpython.version import SUPPORTED, debsorted, vrepr, \                                                       
  File "/usr/share/python/debpython/version.py", line 24, in <module>                                                  
    from ConfigParser import SafeConfigParser                                                                          
ImportError: No module named 'ConfigParser'                                                                            
dpkg: error processing package python-yaml (--configure):                                                              
 subprocess installed post-installation script returned error exit status 1                                            
Setting up python3-yaml (3.11-2) ...                                                                                   
Setting up libmnl-dev (1.0.3-5) ...                                                                                    
Setting up netcat (1.10-41) ...                                                                                        
Setting up uuid-dev:amd64 (2.25.2-6) ...                                                                               
Processing triggers for libc-bin (2.19-18+deb8u4) ...                                                                  
Errors were encountered while processing:                                                                              
 python-yaml                                                                                                           
E: Sub-process /usr/bin/dpkg returned an error code (1)    
```

If I try to install `python3-yaml` with apt-get it fails and shows it was trying to use `ConfigParser` but for python that was renamed for pep8 compliance and should be `configparser`.

Trying to use pip3 to install `python-yaml` fails because it can't find the appropriate package, because (I believe) in python3 the package is `pyyaml`

... of course `pyyaml` is already installed... but for whatever reason it isn't being used for yaml support. 

I don't know if python-yaml and pyyaml are actually equivalent or what.

My best guess is that apt-get is not using python3 and py3 modules properly, not sure why since I have:
```
lrwxrwxrwx 1 root root      18 Apr 21  2016 /usr/bin/python -> /usr/bin/python3.4 
```

Thanks for any advice!

**Comment by l2isbad** [comment]
PyYAML (3.12)

**Comment by ktsaou** [comment]
There is also a pyyaml shipped with netdata.
This should work out of the box, even without pyyaml installed in the system.
Did you try to run python.d.plugin by hand?

**Comment by jtrip** [comment]
I was not running a plugin, I receive this error during installation, sorry if that wasn't clear. It happens during the requirements/prep step. Also note that pyyaml isn't explicitly listed as a requirement, so I can't just remove it from the list, I'm not sure what is requiring it.

Here is a more of the output I get from the installer script
```
sudo apt-get install autoconf autoconf-archive autogen automake curl gcc git libmnl-dev make netcat pkg-config python python3 python3-yaml python-yaml uuid-dev zlib1g-dev 
[sudo] password for jtriplett: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version.
autoconf-archive is already the newest version.
autogen is already the newest version.
automake is already the newest version.
curl is already the newest version.
gcc is already the newest version.
git is already the newest version.
libmnl-dev is already the newest version.
make is already the newest version.
netcat is already the newest version.
pkg-config is already the newest version.
python is already the newest version.
python3 is already the newest version.
python-yaml is already the newest version.
python3-yaml is already the newest version.
uuid-dev is already the newest version.
zlib1g-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 120 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 28, in <module>
    import apt_pkg
ImportError: No module named 'apt_pkg'
Setting up python-yaml (3.11-2) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-yaml (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 python-yaml
E: Sub-process /usr/bin/dpkg returned an error code (1)



We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/firehol/netdata/issues
```
I've also tried to just call apt-get manually with the items listed in this output and the suggested list on the installation page but I receive the same error.

**Comment by jtrip** [comment]
So I've looked into it a little more specifically the `apt-listchanges` error and it I tried to update that but then received the same error, trying to install something else unrelated I am receiving the same error. Looks like my apt-get is broken...

**Comment by jtrip** [comment]
well this just seems to be related to common conflicts with apt-get and python3 and some packages not being marked as conflicting. Quite upsetting IMHO. Closing this issue since it isn't really relevant, thanks for the help though!

**Comment by l2isbad** [comment]
Try to switch to python2

> /usr/bin/python -> /usr/bin/python2.7

install

and then switch to python3 back

> /usr/bin/python -> /usr/bin/python3.4
