### ISSUE TITLE
Postgres configuration error

### ISSUE THREAD

**Issue by harpo** [firehol/netdata#1694]
Hi,
I have the postgres plugin running on two different hosts. with exactly the same configuration except the job name and password. On instance 1 everything works fine, the postgres charts are shown.

Instance 1 conf:
```
postgres:
    name: TEST
    update_every: 1
    priority: 60000
    retries: 5
    database    : 'postgres'
    user        : 'postgres'
    password    : 'password'
    host        : 'localhost'
    port        : 5432

socket:
    name     : 'local'
    user     : 'postgres'
    database : 'postgres'

tcp:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : 'localhost'
    port     : 5432

tcpipv4:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : '127.0.0.1'
    port     : 5432

tcpipv6:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : '::1'
    port     : 5432
```

on instance 2 i get the following errors:

```
2017-02-01 10:01:28: python.d ERROR: postgres_tcpipv6 'bool' object has no attribute 'cursor'
2017-02-01 10:01:28: python.d ERROR: postgres_tcpipv6 check() failed - disabling job
2017-02-01 10:01:28: python.d ERROR: DISABLED: postgres/tcpipv6
2017-02-01 10:01:28: python.d ERROR: postgres_tcpipv4 'bool' object has no attribute 'cursor'
2017-02-01 10:01:28: python.d ERROR: postgres_tcpipv4 check() failed - disabling job
2017-02-01 10:01:28: python.d ERROR: DISABLED: postgres/tcpipv4
2017-02-01 10:01:28: python.d ERROR: postgres_postgres 'bool' object has no attribute 'cursor'
2017-02-01 10:01:28: python.d ERROR: postgres_postgres check() failed - disabling job
2017-02-01 10:01:28: python.d ERROR: DISABLED: postgres/postgres
2017-02-01 10:01:28: python.d ERROR: postgres_tcp 'bool' object has no attribute 'cursor'
2017-02-01 10:01:28: python.d ERROR: postgres_tcp check() failed - disabling job
2017-02-01 10:01:28: python.d ERROR: DISABLED: postgres/tcp
2017-02-01 10:01:28: python.d ERROR: postgres_socket 'bool' object has no attribute 'cursor'
2017-02-01 10:01:28: python.d ERROR: postgres_socket check() failed - disabling job
2017-02-01 10:01:28: python.d ERROR: DISABLED: postgres/socket
```

instance 2 conf:
```
postgres:
    name: PROD
    update_every: 1
    priority: 60000
    retries: 5
    database    : 'postgres'
    user        : 'postgres'
    password    : 'password'
    host        : 'localhost'
    port        : 5432

socket:
    name     : 'local'
    user     : 'postgres'
    database : 'postgres'

tcp:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : 'localhost'
    port     : 5432

tcpipv4:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : '127.0.0.1'
    port     : 5432

tcpipv6:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : '::1'
    port     : 5432
```

I run the current netdata version ab05dd5f3986e7022437a6a48d276ffe90c7bd06 

What does this  'bool' object has no attribute 'cursor' mean? I can't find an error in the config.

**Comment by ktsaou** [comment]
@l2isbad have a look please...

**Comment by l2isbad** [comment]
@harpo 
Can you 
1. Restart postgress
2. Restart netdata
?

**Comment by harpo** [comment]
@l2isbad I restarted netdata and postgres. No change.

**Comment by l2isbad** [comment]
@harpo 
Looks like an error occurs when the plugin tries to connect to postgres.

You can check it yourself in python interpreter

```
/opt/netdata/var/log/netdata$ python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
```


```python
import psycopg2
from psycopg2.extras import DictCursor
params = dict(user='postgres',
                       database='postgres',
                       password=3212,
                      host='localhost',
                      port=5432)
 
connection = psycopg2.connect(**params) # if credentials is correct and posgres is up the error does not occur

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
``` 

Can you check it?

**Comment by harpo** [comment]
@l2isbad Thank you I figured it out. This line was missing in pg_hba.conf on instance 2:
`host    all                     all                             127.0.0.1/32            md5`

But that means that socket (postgres: ident) connections without password don't work as expected?

Because higher up in my pg_hba.conf I have:
`local   all             postgres                                ident`

**Comment by l2isbad** [comment]
@harpo 
Seems you are right! 

Can you remove this line 
https://github.com/firehol/netdata/blob/master/python.d/postgres.chart.py#L206

Then check
- unix socket
- tcp socket

Is there a problem now?

**Comment by harpo** [comment]
@l2isbad I tried the following:

Deleted line 206 from postgres.chart.py
Changed postgres.conf (empty password):
```
postgres:
    name: TEST
    update_every: 1
    priority: 60000
    retries: 5
    database    : 'postgres'
    user        : 'postgres'
    password    : ''
    host        : 'localhost'
    port        : 5432

socket:
    name     : 'local'
    user     : 'postgres'
    database : 'postgres'

tcp:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : 'localhost'
    port     : 5432

tcpipv4:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : '127.0.0.1'
    port     : 5432

tcpipv6:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : '::1'
    port     : 5432
```
and it doesn't work:
```
2017-02-01 16:38:46: python.d ERROR: postgres_tcpipv6 'bool' object has no attribute 'cursor'
2017-02-01 16:38:46: python.d ERROR: postgres_tcpipv6 check() failed - disabling job
2017-02-01 16:38:46: python.d ERROR: DISABLED: postgres/tcpipv6
2017-02-01 16:38:46: python.d ERROR: postgres_tcpipv4 'bool' object has no attribute 'cursor'
2017-02-01 16:38:46: python.d ERROR: postgres_tcpipv4 check() failed - disabling job
2017-02-01 16:38:46: python.d ERROR: DISABLED: postgres/tcpipv4
2017-02-01 16:38:46: python.d ERROR: postgres_postgres 'bool' object has no attribute 'cursor'
2017-02-01 16:38:46: python.d ERROR: postgres_postgres check() failed - disabling job
2017-02-01 16:38:46: python.d ERROR: DISABLED: postgres/postgres
2017-02-01 16:38:46: python.d ERROR: postgres_tcp 'bool' object has no attribute 'cursor'
2017-02-01 16:38:46: python.d ERROR: postgres_tcp check() failed - disabling job
2017-02-01 16:38:46: python.d ERROR: DISABLED: postgres/tcp
2017-02-01 16:38:46: python.d ERROR: postgres_socket 'bool' object has no attribute 'cursor'
2017-02-01 16:38:46: python.d ERROR: postgres_socket check() failed - disabling job
2017-02-01 16:38:46: python.d ERROR: DISABLED: postgres/socket
```

**Comment by l2isbad** [comment]
@harpo 
19.3.5. Ident Authentication

> The ident authentication method works by obtaining the client's operating system user name from an ident server and using it as the allowed database user name (with an optional user name mapping). This is only supported on TCP/IP connections.

**Comment by harpo** [comment]
With 
`local all postgres trust`
it works.
```
2017-02-02 14:02:49: python.d INFO: CHECKED OK: postgres_socket
2017-02-02 14:02:49: python.d INFO: RENAMED: postgres_local , from postgres_socket
```
