### ISSUE TITLE
python.d ERROR: Problem loading elasticsearch invalid syntax

### ISSUE THREAD

**Issue by phaothu** [firehol/netdata#1806]
netdata1.5.0
centos6.5
elasticsearch 2.3.5
netdata error log show 
 python.d ERROR: Problem loading elasticsearch invalid syntax (elasticsearch.chart.py, line 402)

How can i fix it ?

**Comment by l2isbad** [comment]
@phaothu 
You need to change
https://github.com/firehol/netdata/blob/master/python.d/elasticsearch.chart.py#L402

to

```python
dict(['_'.join([string, elem[0]]): elem[1] for elem in dictionary.items()])
```

**Comment by l2isbad** [comment]
@phaothu 
https://github.com/firehol/netdata/pull/1807

**Comment by phaothu** [comment]
had apply #1807 and still 3 error

 File "/usr/libexec/netdata/python.d/elasticsearch.chart.py", line 306, in _get_cluster_health
"to_netdata.update(update_key('health', data))"
  File "/usr/libexec/netdata/python.d/elasticsearch.chart.py", line 359, in _get_node_stats
"to_netdata.update(update_key(key, data['nodes'][node]['indices'].get(key, {})))"
  File "/usr/libexec/netdata/python.d/elasticsearch.chart.py", line 327, in _get_cluster_stats
" to_netdata.update(update_key('count', data['nodes']['count']))"

**Comment by l2isbad** [comment]
Run this from cmd
`/opt/netdata/usr/libexec/netdata/plugins.d]./python.d.plugin 1 debug elasticsearch`

**Comment by phaothu** [comment]
result here:

2017-02-17 11:50:13:  INFO: Using python v2
2017-02-17 11:50:13: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-02-17 11:50:13: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['elasticsearch']
2017-02-17 11:50:13: python.d DEBUG: elasticsearch: loading module configuration: '/etc/netdata/python.d/elasticsearch.conf'
2017-02-17 11:50:13: python.d DEBUG: elasticsearch: reading configuration
2017-02-17 11:50:13: python.d DEBUG: elasticsearch: job added
2017-02-17 11:50:13: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-02-17 11:50:13: python.d INFO: elasticsearch {'http://127.0.0.1:9200/_cluster/health': True, 'http://127.0.0.1:9200/_nodes/_local/stats': True, 'http://127.0.0.1:9200/_cluster/stats': True}
2017-02-17 11:50:13: python.d INFO: elasticsearch Plugin was started successfully
2017-02-17 11:50:13: python.d INFO: CHECKED OK: elasticsearch
2017-02-17 11:50:13: python.d DEBUG: overridden job names: []
2017-02-17 11:50:13: python.d DEBUG: all remaining job objects: [<Service(None, initial daemon)>]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/libexec/netdata/python.d/elasticsearch.chart.py", line 306, in _get_cluster_health
    to_netdata.update(update_key('health', data))
TypeError: 'NoneType' object is not iterable

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/libexec/netdata/python.d/elasticsearch.chart.py", line 359, in _get_node_stats
    to_netdata.update(update_key(key, data['nodes'][node]['indices'].get(key, {})))
TypeError: 'NoneType' object is not iterable

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/libexec/netdata/python.d/elasticsearch.chart.py", line 327, in _get_cluster_stats
    to_netdata.update(update_key('count', data['nodes']['count']))
TypeError: 'NoneType' object is not iterable

**Comment by l2isbad** [comment]
@phaothu 
i made some changes
Check one more time please

**Comment by phaothu** [comment]
working now . Thanks @l2isbad  so much

**Comment by ktsaou** [comment]
perfect. Thank you @l2isbad !
