### ISSUE TITLE
Issue with python script

### ISSUE THREAD

**Issue by DildoShwagginz** [firehol/netdata#1864]
Hi everyone I'm writing a script for serial communication with a device.
I got my script working on a fedora VM and now I'm trying to make it run on a raspi 3.
This is my script:

```
from base import SimpleService
import serial

ORDER = ['status', 'backlight', 'modus', 'inputs']

CHARTS = {
    'status': {
        'options': ['status', ' status', 'On/Off', 'status', 'lcd_data.status', 'line'$
        'lines': [
            ['status', 'status', 'absolute', 1, 1]
        ]},
    'backlight': {
        'options': ['backlight', 'backlight', 'Percentage', 'backlight', 'lcd_data.bac$
        'lines': [
            ['backlight', 'backlight', 'absolute', 1, 1]
        ]},
    'modus': {
	'options': ['modus', 'modus', 'Displaymode', 'modus', 'lcd_data.modus', 'line'$
        'lines': [
            ['modus', 'modus', 'absolute', 1, 1]
        ]},
    'inputs': {
        'options': ['inputs', 'inputs', 'Input', 'input', 'lcd_data.inputs', 'line'],
        'lines': [
            ['k1', 'k1', 'absolute', 1, 1],
            ['k2', 'k2', 'absolute', 1, 1],
            ['k3', 'k3', 'absolute', 1, 1],
            ['k4', 'k4', 'absolute', 1, 1],
        ]}
}

class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.ser = serial.Serial(
            port='/dev/ttyUSB0',
            baudrate=9600,
            parity=serial.PARITY_NONE,
            stopbits=serial.STOPBITS_ONE,
            bytesize=serial.EIGHTBITS,
            timeout = 3
        )

    def push(self, push):
        self.ser.write(push + '\r')
        pull = self.ser.read(11)
        return pull

    def _get_data(self):
        data = {'status': 1, 'backlight': 1, 'modus': 1, 'k1': 1, 'k2': 1, 'k3': 1, 'k$
        self.display_id = "01"
        self.out = self.push(b"ka " + self.display_id.encode() + b" ff")
        if self.out == b"a " + self.display_id.encode() + b" OK01x\r":
                data["status"] = 1
                self.out = self.push(b"kh " + self.display_id.encode() + b" ff")
                self.backlight = int(self.out[7:9], 16)
                data["backlight"] = self.backlight

                self.out = self.push(b"kb " + self.display_id.encode() + b" ff")
                if self.out == b"b " + self.display_id.encode() + b" OK00x\r":
                        data["modus"] = 1
                elif self.out == b"b " + self.display_id.encode() + b" OK01x\r":
                        data["modus"] = 2
                elif self.out == b"b " + self.display_id.encode() + b" OK02x\r":
                        data["modus"] = 3
                elif self.out == b"b " + self.display_id.encode() + b" OK03x\r":
                        data["modus"] = 4
                elif self.out == b"b " + self.display_id.encode() + b" OK04x\r":
                        data["modus"] = 5

                self.out = self.push(b"k1 " + self.display_id.encode() + b" ff")
                if self.out == b"1 " + self.display_id.encode() + b" OK01x\r":
                        data["k1"] = 1
                elif self.out == b"1 " + self.display_id.encode() + b" OK02x\r":
                        data["k1"] = 2
                elif self.out == b"1 " + self.display_id.encode() + b" OK03x\r":
                        data["k1"] = 3
                elif self.out == b"1 " + self.display_id.encode() + b" OK04x\r":
                        data["k1"] = 4
                elif self.out == b"1 " + self.display_id.encode() + b" OK05x\r":
                        data["k1"] = 5

                self.out = self.push(b"k2 " + self.display_id.encode() + b" ff")
                if self.out == b"2 " + self.display_id.encode() + b" OK01x\r":
                        data["k2"] = 1
                elif self.out == b"2 " + self.display_id.encode() + b" OK02x\r":
                        data["k2"] = 2
                elif self.out == b"2 " + self.display_id.encode() + b" OK03x\r":
                        data["k2"] = 3
                elif self.out == b"2 " + self.display_id.encode() + b" OK04x\r":
                        data["k1"] = 4
                elif self.out == b"2 " + self.display_id.encode() + b" OK05x\r":
                        data["k1"] = 5

                self.out = self.push(b"k3 " + self.display_id.encode() + b" ff")
                if self.out == b"3 " + self.display_id.encode() + b" OK01x\r":
                        data["k3"] = 1
                elif self.out == b"3 " + self.display_id.encode() + b" OK02x\r":
                        data["k3"] = 2
                elif self.out == b"3 " + self.display_id.encode() + b" OK03x\r":
                        data["k3"] = 3
                elif self.out == b"3 " + self.display_id.encode() + b" OK04x\r":
                        data["k3"] = 4
                elif self.out == b"3 " + self.display_id.encode() + b" OK05x\r":
                        data["k3"] = 5

                if self.out == b"4 " + self.display_id.encode() + b" OK01x\r":
                        data["k4"] = 1
                elif self.out == b"4 " + self.display_id.encode() + b" OK02x\r":
                        data["k4"] = 2
                elif self.out == b"4 " + self.display_id.encode() + b" OK03x\r":
                        data["k4"] = 3
                elif self.out == b"4 " + self.display_id.encode() + b" OK04x\r":
                        data["k4"] = 4
                elif self.out == b"4 " + self.display_id.encode() + b" OK05x\r":
                        data["k4"] = 5

        elif self.out == b"a " + self.display_id.encode() + b" OK00x\r":
                data["status"] = 0
                self.out = self.push(b"kh " + self.display_id.encode() + b" ff")
                backlight = int(self.out[7:9], 16)
                data["backlight"] = backlight

                self.out = self.push(b"kb " + self.display_id.encode() + b" ff")
                if self.out == b"b " + self.display_id.encode() + b" OK00x\r":
                        data["mode"] = 1
                elif self.out == b"b " + self.display_id.encode() + b" OK01x\r":
                        data["mode"] = 2
                elif self.out == b"b " + self.display_id.encode() + b" OK02x\r":
                        data["mode"] = 3
                elif self.out == b"b " + self.display_id.encode() + b" OK03x\r":
                        data["mode"] = 4
                elif self.out == b"b " + self.display_id.encode() + b" OK04x\r":
                        data["mode"] = 5
                else:
                     	data["mode"] = 0

                self.out = self.push(b"k1 " + self.display_id.encode() + b" ff")
                if self.out == b"1 " + self.display_id.encode() + b" OK01x\r":
                        data["k1"] = 1
                elif self.out == b"1 " + self.display_id.encode() + b" OK02x\r":
                        data["k1"] = 2
                elif self.out == b"1 " + self.display_id.encode() + b" OK03x\r":
                        data["k1"] = 3
                elif self.out == b"1 " + self.display_id.encode() + b" OK04x\r":
                        data["k1"] = 4
                elif self.out == b"1 " + self.display_id.encode() + b" OK05x\r":
                        data["k1"] = 5

                self.out = self.push(b"k2 " + self.display_id.encode() + b" ff")
                if self.out == b"2 " + self.display_id.encode() + b" OK01x\r":
                        data["k2"] = 1
                elif self.out == b"2 " + self.display_id.encode() + b" OK02x\r":
                        data["k2"] = 2
                elif self.out == b"2 " + self.display_id.encode() + b" OK03x\r":
                        data["k2"] = 3
                elif self.out == b"2 " + self.display_id.encode() + b" OK04x\r":
                        data["k2"] = 4
                elif self.out == b"2 " + self.display_id.encode() + b" OK05x\r":
                        data["k2"] = 5
                else:
                     	data["k2"] = 0

                self.out = self.push(b"k3 " + self.display_id.encode() + b" ff")
                if self.out == b"3 " + self.display_id.encode() + b" OK01x\r":
                        data["k3"] = 1
                elif self.out == b"3 " + self.display_id.encode() + b" OK02x\r":
                        data["k3"] = 2
                elif self.out == b"3 " + self.display_id.encode() + b" OK03x\r":
                        data["k3"] = 3
                elif self.out == b"3 " + self.display_id.encode() + b" OK04x\r":
                        data["k3"] = 4
                elif self.out == b"3 " + self.display_id.encode() + b" OK05x\r":
                        data["k3"] = 5
                else:
                     	data["k3"] = 0

                self.out = self.push(b"k4 " + self.display_id.encode() + b" ff")
                if self.out == b"4 " + self.display_id.encode() + b" OK01x\r":
                        data["k4"] = 1
                elif self.out == b"4 " + self.display_id.encode() + b" OK02x\r":
                        data["k4"] = 2
                elif self.out == b"4 " + self.display_id.encode() + b" OK03x\r":
                        data["k4"] = 3
                elif self.out == b"4 " + self.display_id.encode() + b" OK04x\r":
                        data["k4"] = 4
                elif self.out == b"4 " + self.display_id.encode() + b" OK05x\r":
                        data["k4"] = 5
                else:
                     	data["k4"] = 0
	return data
```

And if I try to get it running on the raspi it doesnt work.
error.log looks like this:

> 2017-02-27 16:13:25: netdata: ERROR: Cannot set supplementary groups for user 'netdata' (errno 1, Operation not permitted)
> 
> 2017-02-27 16:13:25: netdata: INFO : netdata started on pid 2839.
> 
> 2017-02-27 16:13:25: netdata: ERROR: HEALTH [eyevis-desktop]: cannot open health file: /var/lib/netdata/health/health-log.db.old (errno 2, No such file or directory)
> 
> 2017-02-27 16:13:25: netdata: INFO : Host 'eyevis-desktop' with guid 'db1ee8fe-fce3-11e6-8726-b827eb4a9d45' initialized, os linux, update every 1, memory mode save, history entries 4036, streaming disabled (to $
> 
> 2017-02-27 16:13:25: netdata: INFO : 2017-02-27 16:13:25: netdata: INFO : PLUGINS.D thread created with task id 28432017-02-27 16:13:25: netdata: INFO : HEALTH thread created with task id 2842
> 
> 2017-02-27 16:13:25: netdata: INFO : netdata initialization completed. Enjoy real-time performance monitoring!
> 
> BACKEND thread created with task id 2841
> 
> 
> 
> 2017-02-27 16:13:25: netdata: INFO : Multi-threaded WEB SERVER thread created with task id 2844
> 
> 2017-02-27 16:13:25: netdata: INFO : Listening on '[0.0.0.0]:19999'
> 
> 2017-02-27 16:13:25: netdata: INFO : Listening on '[::]:19999'
> 
> 2017-02-27 16:13:25: netdata: INFO : BACKEND thread exiting
> 
> 2017-02-27 16:13:25: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/python.d.plugin' running on pid 2846
> 
> 2017-02-27 16:13:25:  INFO: Using python v2
> 
> 2017-02-27 16:13:26:  INFO: YAML output is ordered
> 
> 2017-02-27 16:13:26: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
> 
> Traceback (most recent call last):
> 
>   File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 579, in <module>
> 
>     run()
> 
>   File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 516, in run
> 
>     conf = read_config(configfile)
> 
>   File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 457, in read_config
> 
>     msg.error(str(path), "is malformed:", e)
> 
>   File "/usr/libexec/netdata/python.d/python_modules/msg.py", line 75, in error
> 
>     log_msg("ERROR", *args)
> 
>   File "/usr/libexec/netdata/python.d/python_modules/msg.py", line 38, in log_msg
> 
>     msg = "%s: %s %s: %s" % (timestamp, PROGRAM, str(msg_type), " ".join(args))
> 
> TypeError: sequence item 2: expected string, ParserError found
> 
> 2017-02-27 16:13:26: netdata: ERROR: PLUGINSD: /usr/libexec/netdata/plugins.d/python.d.plugin : read failed.
> 
> 2017-02-27 16:13:26: netdata: ERROR: PLUGINSD: plugin '/usr/libexec/netdata/plugins.d/python.d.plugin' disconnected.
> 
> 2017-02-27 16:13:26: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/python.d.plugin' on pid 2846 stopped after 0 successful data collections (ENDs).
> 
> 2017-02-27 16:13:26: netdata: ERROR: child pid 2846 exited with code 1. (errno 9, Bad file descriptor)
> 
> 2017-02-27 16:13:26: netdata: ERROR: PLUGINSD: '/usr/libexec/netdata/plugins.d/python.d.plugin' exited with error code 1. Disabling it.
> 
> 2017-02-27 16:13:26: netdata: INFO : PLUGINSD: '/usr/libexec/netdata/plugins.d/python.d.plugin' thread exiting
> 

Do you have any ideas?

**Comment by l2isbad** [comment]
So your script works on fedora and fails on raspi? 
I suggest to create a scpit.py file, put your modified code there and run it from shell. Use print() instead of return at the end.

**Comment by l2isbad** [comment]
'options': ['status', ' status', 'On/Off', 'status', 'lcd_data.status', 'line'**$**

**Comment by DildoShwagginz** [comment]
Thank you for your advice I will try debugging it with your method.
Oh the $ is from geedit, the line was too long to show, so it puts a $ there.
My raspi is running ubuntu mate by the way

**Comment by DildoShwagginz** [comment]
I just removed my script totally from the python.d.conf and enabled only example.chart.py.
It looks to me, like Netdata is crashing while its reading the python.d.conf but I have no Idea why. I installed all necessary libraries and python 2 should be installed

**Comment by l2isbad** [comment]
Yeah. Same [here](https://github.com/firehol/netdata/issues/1882)

**Comment by l2isbad** [comment]
@DildoShwagginz 

You need to make sure there is no indentation problems in `python.d.conf`

```yaml
opt1: 'dfdf'
opt2: 'dfdf'
 opt3: 'dfdf'  <--- one space here the problem!
```

**Comment by l2isbad** [comment]
```bash
grep '^ [a-z]' /etc/netdata/python.d.conf
 log_interval: 3600  # extra space added
```

```
./python.d.plugin debig 1 tomcat
2017-03-03 16:35:07:  INFO: Using python v2
2017-03-03 16:35:07:  INFO: YAML output is ordered
2017-03-03 16:35:07: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
Traceback (most recent call last):
  File "./python.d.plugin", line 579, in <module>
    run()
  File "./python.d.plugin", line 516, in run
    conf = read_config(configfile)
  File "./python.d.plugin", line 457, in read_config
    msg.error(str(path), "is malformed:", e)
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/msg.py", line 75, in error
    log_msg("ERROR", *args)
  File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/msg.py", line 38, in log_msg
    msg = "%s: %s %s: %s" % (timestamp, PROGRAM, str(msg_type), " ".join(args))
TypeError: sequence item 2: expected string, ParserError found

```

**Comment by DildoShwagginz** [comment]
Thank you sooo much, problem solved! Thumbs up!

**Comment by ktsaou** [comment]
nice! thank you @l2isbad 
I am closing this.
