### ISSUE TITLE
monitor tomcat , without charts ?

### ISSUE THREAD

**Issue by zhangxin0112** [firehol/netdata#1882]
hi.
i only got the monitor  from tomcat manager ,no netdata charts : 

![1](https://cloud.githubusercontent.com/assets/8244097/23537623/45fa4570-0008-11e7-9971-b503cb816605.png)

/etc/netdata/python.d.conf

enabled: yes
logs_per_interval: 200
log_interval: 3600
example: no
tomcat: yes

/etc/netdata/python.d/tomcat.conf

localhost:
  name : 'local'
  url  : 'http://localhost:8080/manager/status?XML=true'
  user: 'admin'
  pass: 'admin'

localipv4:
  name : 'local'
  url  : 'http://127.0.0.1:8080/manager/status?XML=true'

localipv6:
  name : 'local'
  url  : 'http://[::1]:8080/manager/status?XML=true'

[root@node3 netdata]# ./usr/libexec/netdata/plugins.d/python.d.plugin debug 1 tomcat
2017-03-03 11:52:40:  INFO: Using python v2
2017-03-03 11:52:40: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-03-03 11:52:40: python.d ERROR: /etc/netdata/python.d.conf is not a valid configuration file
2017-03-03 11:52:40: python.d INFO: MODULES_DIR='/opt/monitor/netdata/netdata/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['tomcat']
2017-03-03 11:52:40: python.d ERROR: tomcat: configuration file '/etc/netdata/python.d/tomcat.conf' not found. Using defaults.
2017-03-03 11:52:40: python.d DEBUG: tomcat: setting configuration for only one job
2017-03-03 11:52:40: python.d DEBUG: tomcat: job added
2017-03-03 11:52:40: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-03-03 11:52:40: python.d ERROR: tomcat_local HTTP Error 401: Unauthorized
2017-03-03 11:52:40: python.d DEBUG: tomcat_local 'module' object has no attribute 'ParseError'
2017-03-03 11:52:40: python.d ERROR: tomcat_local HTTP Error 401: Unauthorized
2017-03-03 11:52:40: python.d DEBUG: tomcat_local 'module' object has no attribute 'ParseError'
2017-03-03 11:52:40: python.d ERROR: tomcat_local check() failed - disabling job
2017-03-03 11:52:40: python.d ERROR: DISABLED: tomcat/local
2017-03-03 11:52:40: python.d DEBUG: overridden job names: []
2017-03-03 11:52:40: python.d DEBUG: all remaining job objects: []
2017-03-03 11:52:40: python.d FATAL: no more jobs
DISABLE

`pwd`
/opt/monitor/netdata/netdata
[root@node3 netdata]# ll
total 12
drwxrwxr-x 3 root root 4096 Mar  3 11:49 etc
drwxrwxr-x 5 root root 4096 Mar  3 11:49 usr
drwxrwxr-x 6 root root 4096 Mar  3 11:49 var

`less etc/netdata/netdata.conf`
[global]
        # glibc malloc arena max for plugins = 1
        # glibc malloc arena max for netdata = 1
         config directory = /opt/monitor/netdata/netdata/etc/netdata
         plugins directory = /opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d
         web files directory = /opt/monitor/netdata/netdata/usr/share/netdata/web
         cache directory = /opt/monitor/netdata/netdata/var/cache/netdata
         lib directory = /opt/monitor/netdata/netdata/var/lib/netdata
         log directory = /opt/monitor/netdata/netdata/var/log/netdata
....

i found the error message:
1.
"2017-03-03 11:52:40: python.d ERROR: /etc/netdata/python.d.conf is not a valid configuration file"
2.
2017-03-03 11:52:40: python.d ERROR: tomcat: configuration file '/etc/netdata/python.d/tomcat.conf' not found. Using defaults.
3.
2017-03-03 11:52:40: python.d ERROR: tomcat_local HTTP Error 401: Unauthorized

hope your help.

**Comment by l2isbad** [comment]
Yo @zhangxin0112 

2017-03-03 11:52:40: python.d ERROR: tomcat: configuration file '/etc/netdata/python.d/tomcat.conf' not found. **Using defaults**.

Defaults is [127.0.0.1:8080/manager/status?XML=true](https://github.com/firehol/netdata/blob/master/python.d/tomcat.chart.py#L49) with no http auth.

That is why

> 2017-03-03 11:52:40: python.d ERROR: tomcat_local HTTP Error 401: Unauthorized

**Comment by zhangxin0112** [comment]
so .
you mean conf  ./etc/netdata/python.d/tomcat.conf
url: 'http://127.0.0.1:8080/manager/status?XML=true'
not
url : 'http://localhost:8080/manager/status?XML=true'

what is the web url to monitor tomcat ?
http://127.0.0.1:8080/manager/status?XML=true

**Comment by l2isbad** [comment]
I mean when python.d.plugin can't find configuration file for plugin it will use default values.

From your output i see configuration file was not found so it tries to connect to  127.0.0.1:8080/manager/status?XML=true with no authentication and fails.

**Comment by l2isbad** [comment]
@zhangxin0112 

> CONFIG_DIR is '/etc/netdata' if there is no NETDATA_CONFIG_DIR env var.
> Since you run the command from your shell NEDATA_CONFIG_DIR is missing.

You need to export NETDATA_CONFIG_DIR before run the python.d.plugin.

export NETDATA_CONFIG_DIR=/opt/monitor/netdata/netdata/etc/

**Comment by l2isbad** [comment]
I suggest to comment out all jobs except the one you need in the tomcat configuration file

```yaml
localhost:
    name : 'local'
    url : 'http://localhost:8080/manager/status?XML=true'  # make sure url is correct. Looks like you need to change port to 8075  
    user: 'admin'  # make sure auth params are correct
    pass: 'admin'  # # make sure auth params are correct
```

That is all. If tomcat charts still missing after restart netdata service please post here

```
grep tomcat error.log
```

**Comment by zhangxin0112** [comment]
i found the error.log

2017-03-03 12:57:14: netdata: INFO: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/node.d.plugin' running on pid 74346
2017-03-03 12:57:14: netdata: INFO: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/fping.plugin' running on pid 74347
2017-03-03 12:57:14: netdata: INFO: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' running on pid 74348
2017-03-03 12:57:14: netdata: INFO: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 74349
2017-03-03 12:57:14: netdata: INFO: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' running on pid 74350
.......
2017-03-03 12:57:15: netdata: INFO: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' called DISABLE. Disabling it.
2017-03-03 12:57:15: netdata: INFO: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' on pid 74350 stopped after 0 successful data collections (ENDs).
2017-03-03 12:57:15: netdata: ERROR: child pid 74350 killed by signal 15. (errno 9, Bad file descriptor)
2017-03-03 12:57:15: netdata: ERROR: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' exited with error code -1. Disabling it.
2017-03-03 12:57:15: netdata: INFO: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' thread exiting
Traceback (most recent call last):
  File "/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/python.d.plugin", line 550, in <module>
    run()
  File "/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/python.d.plugin", line 487, in run
    conf = read_config(configfile)
  File "/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/python.d.plugin", line 428, in read_config
    msg.error(str(path), "is malformed:", e)
  File "/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/python.d/python_modules/msg.py", line 75, in error
    log_msg("ERROR", *args)
  File "/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/python.d/python_modules/msg.py", line 38, in log_msg
    msg = "%s: %s %s: %s" % (timestamp, PROGRAM, str(msg_type), " ".join(args))
TypeError: sequence item 2: expected string, ParserError found
2017-03-03 12:57:15: netdata: INFO: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' on pid 74348 stopped after 0 successful data collections (ENDs).
2017-03-03 12:57:15: netdata: ERROR: child pid 74348 exited with code 1. (errno 9, Bad file descriptor)
2017-03-03 12:57:15: netdata: ERROR: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' exited with error code 1. Disabling it.
2017-03-03 12:57:15: netdata: INFO: PLUGINSD: '/opt/rh/netdata/netdata1.5/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' thread exiting
....


this is the key message?

i saw this issue 
https://github.com/firehol/netdata/issues/1864

**Comment by l2isbad** [comment]
Well. It is some weird custom script there (#1864). Also have any custom python scripts?

I see you are not at the latest version of netdata.

And the error from another host. Not the one from the first post..

**Comment by zhangxin0112** [comment]
ye.
i download the lastest version. i install it with cmd 
[root@node3 netdata-master]# ./netdata-installer.sh --install /opt/monitor/netdata
....
 --- Install netdata at system init --- 
 --- Start netdata --- 
[netdata-master]# /sbin/service netdata stop 
netdata: unrecognized service
 FAILED   

[netdata-master]# /sbin/service netdata restart 
netdata: unrecognized service
 FAILED   

[netdata-master]# /sbin/service netdata start 
netdata: unrecognized service
 FAILED   

Starting netdata...
[netdata-master]# /opt/monitor/netdata/netdata/usr/sbin/netdata -P /opt/monitor/netdata/netdata/var/run/netdata.pid 
 OK   

OK. NetData Started!
...

then i clear the log dir and restart it ,the error.log 

......
2017-03-03 13:33:24: netdata: INFO : Listening on '[::]:19999'
2017-03-03 13:33:24: netdata: INFO : PLUGINSD: '/opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/fping.plugin' running on pid 4011
2017-03-03 13:33:24: netdata: INFO : PLUGINSD: '/opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' running on pid 4013
2017-03-03 13:33:24: netdata: INFO : PLUGINSD: '/opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 4015
2017-03-03 13:33:24: netdata: INFO : PLUGINSD: '/opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' running on pid 4016
2017-03-03 13:33:24: netdata: INFO : PLUGINSD: '/opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/node.d.plugin' running on pid 4017
/usr/bin/env: bash: Permission denied
2017-03-03 13:33:24: netdata: ERROR: child pid 4004 exited with code 126. (errno 9, Bad file descriptor)
/usr/bin/env: bash: Permission denied
2017-03-03 13:33:24: netdata: ERROR: PLUGINSD: /opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin : read failed.
2017-03-03 13:33:24: netdata: ERROR: PLUGINSD: plugin '/opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' disconnected.
2017-03-03 13:33:24: netdata: INFO : PLUGINSD: '/opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' on pid 4013 stopped after 0 successful data collections (ENDs).
2017-03-03 13:33:24: netdata: ERROR: child pid 4013 exited with code 126. (errno 9, Bad file descriptor)
2017-03-03 13:33:24: netdata: ERROR: PLUGINSD: '/opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' exited with error code 126. Disabling it.
2017-03-03 13:33:24: netdata: INFO : PLUGINSD: '/opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' thread exiting
/usr/bin/env: bash: Permission denied
2017-03-03 13:33:24: netdata: ERROR: PLUGINSD: /opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/fping.plugin : read failed.
2017-03-03 13:33:24: netdata: ERROR: PLUGINSD: plugin '/opt/monitor/netdata/netdata/usr/libexec/netdata/plugins.d/fping.plugin' disconnected.
......
 question:
i install the netdata in my personal dir (root)
start the netdata (root)
 
/usr/bin/env: bash: Permission denied

**Comment by l2isbad** [comment]
Please show `/etc/netdata/python.d.conf`

**Comment by l2isbad** [comment]
@zhangxin0112 
https://github.com/firehol/netdata/issues/1864
Look at my posts at the end of a topic

**Comment by zhangxin0112** [comment]
Tanks u very much .
Nice work .bro.
:100: @l2isbad
