### ISSUE TITLE
python.d plugin 

### ISSUE THREAD

**Issue by sLuvpreet33** [firehol/netdata#1904]
Please help me in enabling this python.d plugin ?

Firstly, please create a step by step guide to enable this.

I have done this to my files,

https://bpaste.net/show/1a824fbfd8d3

Please tell me if I need to do anything else, and also explain about this 'retries : 10', what does it mean ? I can browse to the page netdatamonitor.com/stub_status , but does not see any kind of graphs there, just some info in text in available.

**Comment by ktsaou** [comment]
Do this:

```
wget 'http://192.168.122.245/stub_status'
wget 'http://netdatamonitor.com/stub_status'
wget 'http://127.0.0.1/stub_status'
```

do they work?
If not, you need an nginx guide to enable `stub_status`.

**Comment by sLuvpreet33** [comment]
luvpreet@luvpreet-vm:/$ sudo wget 'http://netdatamonitor.com/stub_status'
[sudo] password for luvpreet: 
--2017-03-07 12:57:27--  http://netdatamonitor.com/stub_status
Resolving netdatamonitor.com (netdatamonitor.com)... 192.168.122.245
Connecting to netdatamonitor.com (netdatamonitor.com)|192.168.122.245|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 101 [text/plain]
Saving to: ‘stub_status’

100%[=====================================================================================================>] 101         --.-K/s   in 0s      

2017-03-07 12:57:27 (16.8 MB/s) - ‘stub_status’ saved [101/101]





luvpreet@luvpreet-vm:/$ curl 'http://netdatamonitor.com/stub_status'
Active connections: 2 
server accepts handled requests
 13 13 131 
Reading: 0 Writing: 1 Waiting: 1 



The same curl reponse is seen in the browser, the module is working sir, but python.d is not enabled correctly I think.

**Comment by ktsaou** [comment]
ok, let's try this:

```sh
# become user netdata
su -s /bin/sh netdata

# execute the nginx module by hand
/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 nginx
```

Can you post the output?

**Comment by sLuvpreet33** [comment]
2017-03-07 13:36:35:  INFO: Using python v2
2017-03-07 13:36:35:  INFO: YAML output is ordered
2017-03-07 13:36:35: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-03-07 13:36:35: python.d ERROR: /etc/netdata/python.d.conf is not a valid configuration file
2017-03-07 13:36:35: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['nginx']
2017-03-07 13:36:35: python.d DEBUG: nginx: loading module configuration: '/etc/netdata/python.d/nginx.conf'
2017-03-07 13:36:35: python.d ERROR: /etc/netdata/python.d/nginx.conf is not a valid configuration file
2017-03-07 13:36:35: python.d DEBUG: nginx: reading configuration
2017-03-07 13:36:35: python.d DEBUG: nginx: job added
2017-03-07 13:36:35: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-03-07 13:36:35: python.d ERROR: nginx_local HTTP Error 404: Not Found
2017-03-07 13:36:35: python.d ERROR: nginx_local check() failed - disabling job
2017-03-07 13:36:35: python.d ERROR: DISABLED: nginx/local
2017-03-07 13:36:35: python.d DEBUG: overridden job names: []
2017-03-07 13:36:35: python.d DEBUG: all remaining job objects: []
2017-03-07 13:36:35: python.d FATAL: no more jobs
DISABLE

**Comment by sLuvpreet33** [comment]
Here is the pyhton.d.conf file https://bpaste.net/show/ca4f9a6374b9

**Comment by l2isbad** [comment]
@sLuvpreet33 

> 2017-03-07 13:36:35: python.d ERROR: /etc/netdata/python.d.conf is not a valid configuration file
> 2017-03-07 13:36:35: python.d ERROR: /etc/netdata/python.d.conf is not a valid configuration file

```bash
export NETDATA_CONFIG_DIR=/opt/netdata/etc/netdata/   # change DIR if you need to
./python.d.plugin debug 1 tomcat
```

**Comment by sLuvpreet33** [comment]
I didnt get you @l2isbad , how to do that ?

**Comment by l2isbad** [comment]
> CONFIG_DIR is '/etc/netdata' if there is no NETDATA_CONFIG_DIR env var.
> Since you run the command from your shell NEDATA_CONFIG_DIR is missing.
> You need to export NETDATA_CONFIG_DIR before run the python.d.plugin (only when you run it by hand).

```bash
cd /path/to/python.d.plugin
export NETDATA_CONFIG_DIR=/opt/netdata/etc/netdata/ # path to python.d.conf
```
then run python.d.plugin from shell

```bash
./python.d.plugin debug 1 nginx
```

**Comment by sLuvpreet33** [comment]
sir there is no file as ./python.d.plugin , 
    ./python.d.plugin debug 1 nginx , cant be run.

**Comment by l2isbad** [comment]
What is your install directory for netdata?

**Comment by sLuvpreet33** [comment]
/etc/netdata/

**Comment by l2isbad** [comment]
Try to run `python.d.plugin` as root then

I see in your output
`2017-03-07 13:36:35: python.d ERROR: /etc/netdata/python.d.conf is not a valid configuration file`

This means that either the directory is invalid or file is not readable

**Comment by sLuvpreet33** [comment]
When I run  'dpkg -L netdata'    it `says`

dpkg-query: package 'netdata' is not installed
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their

**Comment by sLuvpreet33** [comment]
`luvpreet@luvpreet-vm:/usr/libexec/netdata/plugins.d$ export NETDATA_CONFIG_DIR=/usr/libexec/netdata/plugins.d/python.d.plugin 
luvpreet@luvpreet-vm:/usr/libexec/netdata/plugins.d$ ./python.d.plugin debug 1 nginx
2017-03-07 14:41:28:  INFO: Using python v2
2017-03-07 14:41:29:  INFO: YAML output is ordered
2017-03-07 14:41:29: python.d INFO: reading configuration file: /usr/libexec/netdata/plugins.d/python.d.plugin/python.d.conf
2017-03-07 14:41:29: python.d ERROR: /usr/libexec/netdata/plugins.d/python.d.plugin/python.d.conf is not a valid configuration file
2017-03-07 14:41:29: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/usr/libexec/netdata/plugins.d/python.d.plugin/', UPDATE_EVERY=1, ONLY_MODULES=['nginx']
2017-03-07 14:41:29: python.d ERROR: nginx: configuration file '/usr/libexec/netdata/plugins.d/python.d.plugin/python.d/nginx.conf' not found. Using defaults.
2017-03-07 14:41:29: python.d DEBUG: nginx: setting configuration for only one job
2017-03-07 14:41:29: python.d DEBUG: nginx: job added
2017-03-07 14:41:29: python.d DEBUG: all job objects [<Service(None, initial daemon)>]
2017-03-07 14:41:29: python.d ERROR: nginx_local HTTP Error 404: Not Found
2017-03-07 14:41:29: python.d ERROR: nginx_local check() failed - disabling job
2017-03-07 14:41:29: python.d ERROR: DISABLED: nginx/local
2017-03-07 14:41:29: python.d DEBUG: overridden job names: []
2017-03-07 14:41:29: python.d DEBUG: all remaining job objects: []
2017-03-07 14:41:29: python.d FATAL: no more jobs
DISABLE
`

**Comment by sLuvpreet33** [comment]
What is the correct file and just tell me where to store this file.

**Comment by l2isbad** [comment]
1. if netdata conf directory is /etc/netdata you needn't to export anything. Just run `python.d.plugin debug 1 nginx` **as root**
2. if not you need to export path to conf directory (where netdata.conf, pythond.conf files). Then run **as root**.

**Comment by sLuvpreet33** [comment]
luvpreet@luvpreet-vm:/usr/libexec/netdata/plugins.d$ sudo ./python.d.plugin debug 1 nginx
2017-03-07 14:53:19:  INFO: Using python v2
2017-03-07 14:53:19:  INFO: YAML output is ordered
2017-03-07 14:53:19: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
Traceback (most recent call last):
  File "./python.d.plugin", line 579, in <module>
    run()
  File "./python.d.plugin", line 516, in run
    conf = read_config(configfile)
  File "./python.d.plugin", line 457, in read_config
    msg.error(str(path), "is malformed:", e)
  File "/usr/libexec/netdata/python.d/python_modules/msg.py", line 75, in error
    log_msg("ERROR", *args)
  File "/usr/libexec/netdata/python.d/python_modules/msg.py", line 38, in log_msg
    msg = "%s: %s %s: %s" % (timestamp, PROGRAM, str(msg_type), " ".join(args))
TypeError: sequence item 2: expected string, ParserError found

**Comment by l2isbad** [comment]
Well, look here https://github.com/firehol/netdata/issues/1864 (at the end)

**Comment by sLuvpreet33** [comment]
Take a look now, directory error is solved, there was an identation error actually, but what now ?

luvpreet@luvpreet-vm:/usr/libexec/netdata/plugins.d$ sudo ./python.d.plugin debug 1 nginx
2017-03-07 15:07:19:  INFO: Using python v2
2017-03-07 15:07:19:  INFO: YAML output is ordered
2017-03-07 15:07:19: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-03-07 15:07:19: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['nginx']
2017-03-07 15:07:19: python.d DEBUG: nginx: loading module configuration: '/etc/netdata/python.d/nginx.conf'
2017-03-07 15:07:19: python.d DEBUG: nginx: reading configuration
2017-03-07 15:07:19: python.d DEBUG: nginx/RemoteNginx: job added
2017-03-07 15:07:19: python.d DEBUG: nginx/localipv4: job added
2017-03-07 15:07:19: python.d DEBUG: nginx/localipv6: job added
2017-03-07 15:07:19: python.d DEBUG: all job objects [<Service(RemoteNginx, initial daemon)>, <Service(localipv4, initial daemon)>, <Service(localipv6, initial daemon)>]
2017-03-07 15:07:19: python.d ERROR: nginx_RemoteNginx HTTP Error 404: Not Found
2017-03-07 15:07:19: python.d ERROR: nginx_RemoteNginx check() failed - disabling job
2017-03-07 15:07:19: python.d ERROR: DISABLED: nginx/RemoteNginx
2017-03-07 15:07:19: python.d ERROR: nginx_localipv4 HTTP Error 404: Not Found
2017-03-07 15:07:19: python.d ERROR: nginx_localipv4 check() failed - disabling job
2017-03-07 15:07:19: python.d ERROR: DISABLED: nginx/localipv4
2017-03-07 15:07:19: python.d ERROR: nginx_localipv6 <urlopen error [Errno -2] Name or service not known>
2017-03-07 15:07:19: python.d ERROR: nginx_localipv6 check() failed - disabling job
2017-03-07 15:07:19: python.d ERROR: DISABLED: nginx/localipv6
2017-03-07 15:07:19: python.d DEBUG: overridden job names: []
2017-03-07 15:07:19: python.d DEBUG: all remaining job objects: []
2017-03-07 15:07:19: python.d FATAL: no more jobs
DISABLE

**Comment by sLuvpreet33** [comment]
Hey, the command `sudo ./python.d.plugin debug 1 nginx` is working,
here is the output and it keeps on refreshing.

but the graphs are still not being shown on netdatamonitot.com/stub_status

2017-03-07 15:21:35: python.d DEBUG: nginx_Reverse_proxy sleeping for 0.998315095901 secs to reach frequency of 1.0 secs, now: 1488880296.0  next: 1488880297.0  penalty: 0
BEGIN nginx_Reverse_proxy.connections 999507
SET active = 2
END 
BEGIN nginx_Reverse_proxy.requests 999507
SET requests = 122
END 
BEGIN nginx_Reverse_proxy.connection_status 999507
SET reading = 0
SET writing = 1
SET waiting = 1
END 
BEGIN nginx_Reverse_proxy.connect_rate 999507
SET accepts = 40
SET handled = 40
END

**Comment by l2isbad** [comment]
> url  : 'http://netdatamonitor.com/stub_status'

Better to use ip address in url. Restart netdata.service and look for nginx_Reverse_proxy in the dashboard.

**Comment by sLuvpreet33** [comment]
I din't get that dashboard thing, please explain

**Comment by l2isbad** [comment]
dashboard is http://netdata.ip:19999

```python
ReverseNginx:  # i assume this one is correct
  name : 'Reverse_Proxy'
  url  : 'http://192.168.122.245/stub_status'


#ReverseNginx:
#  name : 'Reverse_proxy'
#  url  : 'http://netdatamonitor.com/stub_status'
#  retries : 10

#ReverseNginx:
#  name : 'Reverse_Proxy'
#  url  : 'http://127.0.0.1/stub_status'
#  retries : 10
```

restart netdata.service then

**Comment by sLuvpreet33** [comment]
no graphs still !!

**Comment by l2isbad** [comment]
Please show netdata error.log.
```bash
cd to netdata log dir.
cp /dev/nul error.log
systemctl restart netdata.service
grep nginx error.log
```

**Comment by sLuvpreet33** [comment]
I couldn't find the error logs of netdata.

**Comment by sLuvpreet33** [comment]
Is there any solution to it ?

**Comment by l2isbad** [comment]
> I couldn't find the error logs of netdata.

check here

/var/log/netdata/

**Comment by sLuvpreet33** [comment]
found error logs,

This is the result of grep nginx error.log


2017-03-07 20:08:32: charts.d: INFO: nginx: is disabled. Add a line with nginx=force in /etc/netdata/charts.d.conf to enable it (or remove the line that disables it).
2017-03-07 20:08:34: python.d INFO: web_log_nginx_log Collected data: ['url', 'code', 'bytes_sent', 'method', 'address']
2017-03-07 20:08:34: python.d INFO: CHECKED OK: web_log_nginx_log
2017-03-07 20:08:34: python.d INFO: RENAMED: web_log_nginx , from web_log_nginx_log
2017-03-07 20:08:37: python.d ERROR: web_log_nginx_log2 /var/log/nginx/localhost.access_log not readable or not exist
2017-03-07 20:08:37: python.d ERROR: web_log_nginx_log2 check() failed - disabling job
2017-03-07 20:08:37: python.d ERROR: DISABLED: web_log/nginx_log2
2017-03-07 20:08:37: python.d INFO: CHECKED OK: nginx_RemoteNginx
2017-03-07 20:08:37: python.d INFO: RENAMED: nginx_Reverse_proxy , from nginx_RemoteNginx

**Comment by l2isbad** [comment]
python.d INFO: **CHECKED OK**: nginx_RemoteNginx

Do you see any **nginx_RemoteNginx** thing in the dashboard menu (http://netdata.ip:19999)

**Comment by sLuvpreet33** [comment]
![screenshot from 2017-03-07 20-25-36](https://cloud.githubusercontent.com/assets/23127804/23662023/4ea09f7a-0374-11e7-86b6-ac29c3f06f32.png)

have a look

**Comment by l2isbad** [comment]
I mean the thing on the right (menu). 
![screenshot_20170307_235742](https://cloud.githubusercontent.com/assets/22274335/23662107/df405e9a-0391-11e7-9128-90c2172c9290.png)

**Comment by sLuvpreet33** [comment]
Actually, this option is not there on my dashboard, and neither that (?help) option.

Was it released in a recent update or it is due to any other reason ?

**Comment by l2isbad** [comment]
Change your screen resolution...

**Comment by l2isbad** [comment]
![screenshot_20170308_002113](https://cloud.githubusercontent.com/assets/22274335/23663176/2a3c2fca-0395-11e7-8b27-a56e9b4c0c19.png)

**Comment by sLuvpreet33** [comment]
yeah I see the help section, but nthng else 
![screenshot from 2017-03-07 20-53-18](https://cloud.githubusercontent.com/assets/23127804/23663327/42ef9c9a-0378-11e7-9c58-8b1bb36d3e3a.png)

**Comment by l2isbad** [comment]
Because of your screen size. No space for menu.

**Comment by l2isbad** [comment]
This screen is vnc session from a vm, right?

To see netdata in your browser (no a vm browser)
ssh -L 127.0.0.1:19998:127.0.0.1:19999 <user>@<ip address of VM>

http://127.0.0.1:19998

**Comment by sLuvpreet33** [comment]
well, that was one very simple and amazing idea !! Thank you very ,uch

**Comment by l2isbad** [comment]
You can put configuration for local port forwarding to the  `/home/<user>/.ssh/config`

```bash
Host <hostname>
HostName <ip address>
User <username>
LocalForward 127.0.0.1:19998 127.0.0.1:19999
```

then `ssh <hostname>`

**Comment by sLuvpreet33** [comment]
Thank you for the suggestion.

**Comment by sLuvpreet33** [comment]
https://github.com/firehol/netdata/tree/master/python.d#nginx_log

Where to specify these paths, I mean which file, can you tell me here?

**Comment by l2isbad** [comment]
**nginx_log** was replaced by **[web_log](https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf)**
Check `web_log_nginx` in dashboard menu. It maybe already there.

**Comment by sLuvpreet33** [comment]
yes, it was.

**Comment by sLuvpreet33** [comment]
Can we monitor a specific port on our machine by using netdata?

**Comment by l2isbad** [comment]
I think no. But please describe it in detail. How it supposed to work? What is "monitor a specific port"? Open or not?

**Comment by sLuvpreet33** [comment]
For example, if django server is running on port 8000, then can we monitor
that port '8000' so that we can see how many requests are being passed on
to that port, and how many are being ignored ?

Something like that.

**Comment by l2isbad** [comment]
I think you can use FireQos to achieve this. [Take a look](http://london.my-netdata.io/default.html#menu_tc_submenu_eth0;theme=slate;help=true).
[ And here](https://github.com/firehol/netdata/wiki/Monitor-application-bandwidth-with-Linux-QoS).

I mean you can graph all tcp port 8000 syn packets.

**Comment by sLuvpreet33** [comment]
It says that firehol must be installed to use FireQos , and iprange must be
installed to use it.
But I'm having trouble installing iprange.

I downloaded its tar file and unzip it, ran ./configure(it runs) but then,
make && make install gives me error.

Here is the O/P of make && make install

make  all-am
make[1]: Entering directory `/home/luvpreet/Downloads/iprange-1.0.3'
make[1]: Leaving directory `/home/luvpreet/Downloads/iprange-1.0.3'
make[1]: Entering directory `/home/luvpreet/Downloads/iprange-1.0.3'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c iprange '/usr/local/bin'
/usr/bin/install: cannot remove ‘/usr/local/bin/iprange’: Permission denied
make[1]: *** [install-binPROGRAMS] Error 1
make[1]: Leaving directory `/home/luvpreet/Downloads/iprange-1.0.3'
make: *** [install-am] Error 2

**Comment by l2isbad** [comment]
I am not sure you need `iprange`. Anyway problems with iprange -  https://github.com/firehol/iprange/issues

**Comment by sLuvpreet33** [comment]
https://github.com/firehol/netdata/wiki/Monitor-application-bandwidth-with-Linux-QoS#qos-in-linux-have-you-lost-your-mind

look here, they are saying to install Firehol to write your own
FireQoS(which is written just below that) to enable the plugin, and to
install Firehol, I need "iprange".

Am I heading in the wrong direction ?

**Comment by ktsaou** [comment]
I have not followed the entire thread, so excuse me if I say something out of context:

fireqos will help you monitor the bandwidth of specific ports. If you have web server log files for the requests these ports serve, you can also use web_log plugin (it will not be as accurate as fireqos, but it will give you an indication).

**Comment by sLuvpreet33** [comment]
Okay I have got Quality of Service(QoS) on my dashboard.

I can see the ssh service in my graphs in QoS which is running on port 22.

Is there any way I can add any port(like 8000) to Fireqos.conf, and see the
live status of that port in QoS ?

**Comment by ktsaou** [comment]
Yes of course. Follow the [fireqos tutorial](https://github.com/firehol/firehol/wiki/FireQOS-Tutorial) to learn how you can configure fireqos.

**Comment by sLuvpreet33** [comment]
What is the difference between eth0 world under Quality of Service and eth0
under Network Interfaces on the dashboard ?

**Comment by ktsaou** [comment]
QoS breaks down the interface  traffic per service/class you define in fireqos.conf - other than that they are the same.

**Comment by sLuvpreet33** [comment]
Well, thank you for that, and netdata is awesome !!

But sometimes(in a span of 2 days, but gets automatically resolved after 5
mins), this issue comes up.

**Comment by ktsaou** [comment]
thanks!

> But sometimes(in a span of 2 days, but gets automatically resolved after 5
> mins), this issue comes up.

which issue?

**Comment by sLuvpreet33** [comment]
![screenshot from 2017-03-10 18-48-33](https://cloud.githubusercontent.com/assets/23127804/23813116/634dbf48-0603-11e7-89cf-fd51a607ff43.png)

**Comment by ktsaou** [comment]
hm... strange...

1. does it happen only when you start firefox or at any point?
2. If you hit F5 is it downloaded successfully?
3. Do you have a log at `/var/log/netdata/access.log` about this? Can you post it?

**Comment by sLuvpreet33** [comment]
It happens when I restart the netdata service.

**Comment by ktsaou** [comment]
ok. let check I understood this right:

1. netdata is started and is working
2. firefox displays already the netdata dashboard
3. you restart netdata.service and you get this?

Could you please give me the steps to reproduce it?

**Comment by sLuvpreet33** [comment]
channel 4: open failed: connect failed: Connection refused

This is the error always. It happens when I make changes to Fireqos.conf
and restart netdata after that.
Please tell me if the problem is in netdata or my system, and the solution
also.

**Comment by sLuvpreet33** [comment]
![screenshot from 2017-03-13 04-04-11](https://cloud.githubusercontent.com/assets/23127804/23836684/300004ac-07a2-11e7-85f4-b5a1e5b2c48b.png)


This is what it shows after some time. 

Takes some time and displays the regular correct view after that.

**Comment by sLuvpreet33** [comment]
Hi Costa, did you get anything for this problem?

**Comment by sLuvpreet33** [comment]
Did anybody get something on it?

**Comment by sLuvpreet33** [comment]
![screenshot from 2017-03-24 18-19-47](https://cloud.githubusercontent.com/assets/23127804/24294931/91d6dc8a-10be-11e7-8f76-6abebbec2a02.png)

What is this machine-ubuntu 14.04 ?
Is this my virtual machine ?

**Comment by sLuvpreet33** [comment]
![screenshot from 2017-03-24 18-22-22](https://cloud.githubusercontent.com/assets/23127804/24294990/dc57af00-10be-11e7-855c-72c86b1038f7.png)

And suddenly other server's netdata has gone empty, why so?😕
