### ISSUE TITLE
haproxy check on another host, fails 

### ISSUE THREAD

**Issue by trustbyte** [firehol/netdata#1997]
Hey,

Trying to check haproxy on another host (not localhost) via_url, with user and password and it fails with this error:
Any ideas?

Thanks!

```
bash-4.2$ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 0 haproxy
2017-03-22 20:44:11:  INFO: Using python v2
2017-03-22 20:44:11:  INFO: YAML output is ordered
2017-03-22 20:44:11: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-03-22 20:44:11: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=0, ONLY_MODULES=['haproxy']
2017-03-22 20:44:11: python.d ERROR: haproxy/via_url: cannot start job: 'float modulo
Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 596, in <module>
    run()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 589, in run
    charts.check()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 368, in check
    while i < len(self.jobs):
TypeError: object of type 'NoneType' has no len()
```

```
bash-4.2$ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1 haproxy
2017-03-22 20:44:14:  INFO: Using python v2
2017-03-22 20:44:14:  INFO: YAML output is ordered
2017-03-22 20:44:14: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-03-22 20:44:15: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['haproxy']
2017-03-22 20:44:15: python.d ERROR: DISABLED: haproxy/via_url
2017-03-22 20:44:15: python.d ERROR: haproxy_via_url cannot find check() function or it thrown unhandled exception.
2017-03-22 20:44:15: python.d FATAL: no more jobs
DISABLE

```

**Comment by l2isbad** [comment]
@trustbyte 
It's a bug. I will fix it. Thx for reporting.

**Comment by l2isbad** [comment]
@trustbyte 
I think i fix it in https://github.com/firehol/netdata/pull/2001
Can you test it please?

**Comment by ktsaou** [comment]
the issue has been closed automatically with the merge of the fix.
if it does not work, open it again.

**Comment by trustbyte** [comment]
@l2isbad yeap, checked, it works now. thanks!
