### ISSUE TITLE
LogService question

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#2340]
I have a few custom python.d.plugin modules.
I updated netdata (it was a month old or so) and now I get this:

```
/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 XXX
2017-06-15 13:33:52:  INFO: Using python v2
2017-06-15 13:33:52:  INFO: YAML output is ordered
2017-06-15 13:33:52: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2017-06-15 13:33:52: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['XXX']
2017-06-15 13:33:52: python.d ERROR: XXX: configuration file '/etc/netdata/python.d/XXX.conf' not found. Using defaults.
2017-06-15 13:33:52: python.d DEBUG: XXX: setting configuration for only one job
2017-06-15 13:33:52: python.d ERROR: XXX: cannot start job: 'object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 596, in <module>
    run()
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 588, in run
    charts = PythonCharts(modules, MODULES_DIR, CONFIG_DIR + "python.d/", disabled, enabled, default_run)
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 140, in __init__
    for job in self.jobs:
TypeError: 'NoneType' object is not iterable
```

@l2isbad any ideas how to fix this?

Keep in mind this kind of problem takes down the whole python.d.plugin. It should disable just this module and continue. Instead the whole python.d.plugin was stopped.

**Comment by ktsaou** [comment]
> Keep in mind this kind of problem takes down the whole python.d.plugin. It should disable just this module and continue. Instead the whole python.d.plugin was stopped.

I don't know if this also the case for old python.d.plugin modules that are now removed (eg `nginx_log`, `apache_cache`, etc). If this happens with them too, it would probably be a good idea to keep the files in the repo and install them as usual, but with compatible code that will just disable them, instead of breaking the whole plugin.

**Comment by l2isbad** [comment]
> any ideas how to fix this?

Do you copy the old `nginx_log` plugin to create your own? 😄 
If so 

```python
def __init__(self, configuration=None, name=None):
        LogService.__init__(self, configuration=configuration, name=name)
        if len(self.log_path) == 0:                                 # remove this 
            self.log_path = "/var/log/nginx/access.log"  # thing, it makes no sense
```

**Comment by l2isbad** [comment]
>  If this happens with them too

well, they are disabled. I am not sure how they can break the whole plugin is such case.

**Comment by l2isbad** [comment]
> It should disable just this module and continue

This should work like you say after[ the change to](https://github.com/firehol/netdata/blob/master/plugins.d/python.d.plugin#L313) `continue`

**Comment by ktsaou** [comment]
> Do you copy the old nginx_log plugin to create your own? 
> If so and plugin has no conf/jobs

yes! this was it! thanks!

**Comment by ktsaou** [comment]
Do you want me to mark this bug?
