### ISSUE TITLE
elasticsearch monitoring

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#2443]
@l2isbad I am trying to setup elasticsearch monitoring and I get this:

```
# /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug elasticsearch
2017-07-11 14:54:39:  INFO: Using python v2
2017-07-11 14:54:39:  INFO: YAML output is ordered
2017-07-11 14:54:39: python.d INFO: reading configuration file: /usr/libexec/netdata/plugins.d/../../../../etc/netdata/python.d.conf
2017-07-11 14:54:39: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/usr/libexec/netdata/plugins.d/../../../../etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['elasticsearch']
2017-07-11 14:54:39: python.d DEBUG: elasticsearch: loading module configuration: '/usr/libexec/netdata/plugins.d/../../../../etc/netdata/python.d/elasticsearch.conf'
2017-07-11 14:54:39: python.d DEBUG: elasticsearch: reading configuration
2017-07-11 14:54:39: python.d DEBUG: elasticsearch/local: job added
2017-07-11 14:54:39: python.d DEBUG: all job objects [<Service(local, initial daemon)>]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/libexec/netdata/python.d/elasticsearch.chart.py", line 443, in _get_node_stats_
    / to_netdata['max_file_descriptors'] * 1000)
KeyError: 'max_file_descriptors'
```

elasticsearch is v1.7.3

any ideas?

**Comment by ktsaou** [comment]
This is the response of elasticsearch:

```json
{
              "cluster_name": "SSSSSSSS",
              "nodes": {
                             "sdfgdsfgdsfgsdfg": {
                                           "timestamp": 1499774079903,
                                           "name": "ssss01",
                                           "transport_address": "inet[/1.1.1.1:9300]",
                                           "host": "ssssssss",
                                           "ip": ["inet[/1.1.1.1:9300]",
                                           "NONE"],
                                           "indices": {
                                                          "docs": {
                                                                        "count": 5897762,
                                                                        "deleted": 6406424
                                                          },
                                                          "store": {
                                                                        "size_in_bytes": 25797216377,
                                                                        "throttle_time_in_millis": 42305
                                                          },
                                                          "indexing": {
                                                                        "index_total": 13891,
                                                                        "index_time_in_millis": 28394,
                                                                        "index_current": 0,
                                                                        "delete_total": 0,
                                                                        "delete_time_in_millis": 0,
                                                                        "delete_current": 0,
                                                                        "noop_update_total": 0,
                                                                        "is_throttled": false,
                                                                        "throttle_time_in_millis": 0
                                                          },
                                                          "get": {
                                                                        "total": 5371,
                                                                        "time_in_millis": 2039,
                                                                        "exists_total": 5330,
                                                                        "exists_time_in_millis": 2036,
                                                                        "missing_total": 41,
                                                                        "missing_time_in_millis": 3,
                                                                        "current": 0
                                                          },
                                                          "search": {
                                                                        "open_contexts": 0,
                                                                        "query_total": 41901,
                                                                        "query_time_in_millis": 204704,
                                                                        "query_current": 0,
                                                                        "fetch_total": 8297,
                                                                        "fetch_time_in_millis": 6087,
                                                                        "fetch_current": 0
                                                          },
                                                          "merges": {
                                                                        "current": 0,
                                                                        "current_docs": 0,
                                                                        "current_size_in_bytes": 0,
                                                                        "total": 878,
                                                                        "total_time_in_millis": 172786,
                                                                        "total_docs": 701787,
                                                                        "total_size_in_bytes": 1046403097
                                                          },
                                                          "refresh": {
                                                                        "total": 11308,
                                                                        "total_time_in_millis": 73555
                                                          },
                                                          "flush": {
                                                                        "total": 934,
                                                                        "total_time_in_millis": 18013
                                                          },
                                                          "warmer": {
                                                                        "current": 0,
                                                                        "total": 22301,
                                                                        "total_time_in_millis": 3147
                                                          },
                                                          "filter_cache": {
                                                                        "memory_size_in_bytes": 72884488,
                                                                        "evictions": 112907
                                                          },
                                                          "id_cache": {
                                                                        "memory_size_in_bytes": 0
                                                          },
                                                          "fielddata": {
                                                                        "memory_size_in_bytes": 29092552,
                                                                        "evictions": 0
                                                          },
                                                          "percolate": {
                                                                        "total": 0,
                                                                        "time_in_millis": 0,
                                                                        "current": 0,
                                                                        "memory_size_in_bytes": -1,
                                                                        "memory_size": "-1b",
                                                                        "queries": 0
                                                          },
                                                          "completion": {
                                                                        "size_in_bytes": 0
                                                          },
                                                          "segments": {
                                                                        "count": 1881,
                                                                        "memory_in_bytes": 91457106,
                                                                        "index_writer_memory_in_bytes": 0,
                                                                        "index_writer_max_memory_in_bytes": 196001244,
                                                                        "version_map_memory_in_bytes": 0,
                                                                        "fixed_bit_set_memory_in_bytes": 0
                                                          },
                                                          "translog": {
                                                                        "operations": 310,
                                                                        "size_in_bytes": 1167
                                                          },
                                                          "suggest": {
                                                                        "total": 0,
                                                                        "time_in_millis": 0,
                                                                        "current": 0
                                                          },
                                                          "query_cache": {
                                                                        "memory_size_in_bytes": 0,
                                                                        "evictions": 0,
                                                                        "hit_count": 0,
                                                                        "miss_count": 0
                                                          },
                                                          "recovery": {
                                                                        "current_as_source": 0,
                                                                        "current_as_target": 0,
                                                                        "throttle_time_in_millis": 0
                                                          }
                                           },
                                           "os": {
                                                          "timestamp": 1499774080097,
                                                          "uptime_in_millis": 7373,
                                                          "load_average": [0.14,
                                                          0.35,
                                                          0.33],
                                                          "cpu": {
                                                                        "sys": 0,
                                                                        "user": 1,
                                                                        "idle": 97,
                                                                        "usage": 1,
                                                                        "stolen": 0
                                                          },
                                                          "mem": {
                                                                        "free_in_bytes": 1786249216,
                                                                        "used_in_bytes": 2363219968,
                                                                        "free_percent": 72,
                                                                        "used_percent": 27,
                                                                        "actual_free_in_bytes": 3001446400,
                                                                        "actual_used_in_bytes": 1148022784
                                                          },
                                                          "swap": {
                                                                        "used_in_bytes": 0,
                                                                        "free_in_bytes": 11161038848
                                                          }
                                           },
                                           "process": {
                                                          "timestamp": 1499774079909,
                                                          "open_file_descriptors": 4889,
                                                          "cpu": {
                                                                        "percent": 7,
                                                                        "sys_in_millis": 110770,
                                                                        "user_in_millis": 798680,
                                                                        "total_in_millis": 909450
                                                          },
                                                          "mem": {
                                                                        "resident_in_bytes": 1148645376,
                                                                        "share_in_bytes": 276176896,
                                                                        "total_virtual_in_bytes": 7550394368
                                                          }
                                           },
                                           "jvm": {
                                                          "timestamp": 1499774079913,
                                                          "uptime_in_millis": 7325213,
                                                          "mem": {
                                                                        "heap_used_in_bytes": 551006576,
                                                                        "heap_used_percent": 53,
                                                                        "heap_committed_in_bytes": 805371904,
                                                                        "heap_max_in_bytes": 1038876672,
                                                                        "non_heap_used_in_bytes": 104554792,
                                                                        "non_heap_committed_in_bytes": 106135552,
                                                                        "pools": {
                                                                                      "young": {
                                                                                                     "used_in_bytes": 68248192,
                                                                                                     "max_in_bytes": 279183360,
                                                                                                    "peak_used_in_bytes": 71630848,
                                                                                                     "peak_max_in_bytes": 279183360
                                                                                      },
                                                                                      "survivor": {
                                                                                                     "used_in_bytes": 6783856,
                                                                                                     "max_in_bytes": 34865152,
                                                                                                    "peak_used_in_bytes": 8912896,
                                                                                                     "peak_max_in_bytes": 34865152
                                                                                      },
                                                                                      "old": {
                                                                                                     "used_in_bytes": 475974528,
                                                                                                     "max_in_bytes": 724828160,
                                                                                                    "peak_used_in_bytes": 546691456,
                                                                                                     "peak_max_in_bytes": 724828160
                                                                                      }
                                                                        }
                                                          },
                                                          "threads": {
                                                                        "count": 75,
                                                                        "peak_count": 85
                                                          },
                                                          "gc": {
                                                                        "collectors": {
                                                                                      "young": {
                                                                                                     "collection_count": 839,
                                                                                                    "collection_time_in_millis": 21170
                                                                                      },
                                                                                      "old": {
                                                                                                     "collection_count": 18,
                                                                                                    "collection_time_in_millis": 1337
                                                                                      }
                                                                        }
                                                          },
                                                          "buffer_pools": {
                                                                        "direct": {
                                                                                      "count": 104,
                                                                                      "used_in_bytes": 9531665,
                                                                                      "total_capacity_in_bytes": 9531665
                                                                        },
                                                                        "mapped": {
                                                                                      "count": 1222,
                                                                                      "used_in_bytes": 2796676117,
                                                                                      "total_capacity_in_bytes": 2796676117
                                                                        }
                                                          }
                                           },
                                           "thread_pool": {
                                                          "percolate": {
                                                                        "threads": 0,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 0,
                                                                        "completed": 0
                                                          },
                                                          "fetch_shard_started": {
                                                                        "threads": 1,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 8,
                                                                        "completed": 210
                                                          },
                                                          "listener": {
                                                                        "threads": 2,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 2,
                                                                        "completed": 126
                                                          },
                                                          "index": {
                                                                        "threads": 4,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 4,
                                                                        "completed": 3242
                                                          },
                                                          "refresh": {
                                                                        "threads": 2,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 2,
                                                                        "completed": 10976
                                                          },
                                                          "suggest": {
                                                                        "threads": 0,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 0,
                                                                        "completed": 0
                                                          },
                                                          "generic": {
                                                                        "threads": 1,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 5,
                                                                        "completed": 1067
                                                         },
                                                          "warmer": {
                                                                        "threads": 2,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 2,
                                                                        "completed": 11112
                                                          },
                                                          "search": {
                                                                        "threads": 7,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 7,
                                                                        "completed": 52993
                                                          },
                                                          "flush": {
                                                                        "threads": 2,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 2,
                                                                        "completed": 9788
                                                          },
                                                          "optimize": {
                                                                        "threads": 0,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 0,
                                                                        "completed": 0
                                                          },
                                                          "fetch_shard_store": {
                                                                        "threads": 0,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 0,
                                                                        "completed": 0
                                                          },
                                                          "management": {
                                                                        "threads": 5,
                                                                        "queue": 0,
                                                                        "active": 2,
                                                                        "rejected": 0,
                                                                        "largest": 5,
                                                                        "completed": 51892
                                                          },
                                                          "get": {
                                                                        "threads": 4,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 4,
                                                                        "completed": 1982
                                                          },
                                                          "merge": {
                                                                        "threads": 2,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 2,
                                                                        "completed": 878
                                                          },
                                                          "bulk": {
                                                                        "threads": 4,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 4,
                                                                        "completed": 8329
                                                          },
                                                          "snapshot": {
                                                                        "threads": 0,
                                                                        "queue": 0,
                                                                        "active": 0,
                                                                        "rejected": 0,
                                                                        "largest": 0,
                                                                        "completed": 0
                                                          }
                                           },
                                           "network": {
                                                          "tcp": {
                                                                        "active_opens": 1331,
                                                                        "passive_opens": 7472,
                                                                        "curr_estab": 42,
                                                                        "in_segs": 132027,
                                                                        "out_segs": 132715,
                                                                        "retrans_segs": 145,
                                                                        "estab_resets": 27,
                                                                        "attempt_fails": 457,
                                                                        "in_errs": 0,
                                                                        "out_rsts": 716
                                                          }
                                           },
                                           "fs": {
                                                          "timestamp": 1499774079913,
                                                          "total": {
                                                                        "total_in_bytes": 259441455104,
                                                                        "free_in_bytes": 227382202368,
                                                                        "available_in_bytes": 214179741696,
                                                                        "disk_reads": 50118,
                                                                        "disk_writes": 89795,
                                                                        "disk_io_op": 139913,
                                                                        "disk_read_size_in_bytes": 1012724736,
                                                                        "disk_write_size_in_bytes": 2366656512,
                                                                        "disk_io_size_in_bytes": 3379381248,
                                                                        "disk_queue": "0",
                                                                        "disk_service_time": "0.4"
                                                          },
                                                          "data": [{
                                                                        "path": "/var/lib/sssss/sssss/nodes/0",
                                                                        "mount": "/",
                                                                        "dev": "/dev/sda1",
                                                                        "type": "ext4",
                                                                        "total_in_bytes": 259441455104,
                                                                        "free_in_bytes": 227382202368,
                                                                        "available_in_bytes": 214179741696,
                                                                        "disk_reads": 50118,
                                                                        "disk_writes": 89795,
                                                                        "disk_io_op": 139913,
                                                                        "disk_read_size_in_bytes": 1012724736,
                                                                        "disk_write_size_in_bytes": 2366656512,
                                                                        "disk_io_size_in_bytes": 3379381248,
                                                                        "disk_queue": "0",
                                                                        "disk_service_time": "0.4"
                                                          }]
                                           },
                                           "transport": {
                                                          "server_open": 13,
                                                          "rx_count": 6,
                                                          "rx_size_in_bytes": 1512,
                                                          "tx_count": 6,
                                                          "tx_size_in_bytes": 1512
                                           },
                                           "http": {
                                                          "current_open": 4,
                                                          "total_opened": 389
                                           },
                                           "breakers": {
                                                          "fielddata": {
                                                                        "limit_size_in_bytes": 623326003,
                                                                        "limit_size": "594.4mb",
                                                                        "estimated_size_in_bytes": 29092552,
                                                                        "estimated_size": "27.7mb",
                                                                        "overhead": 1.03,
                                                                        "tripped": 0
                                                          },
                                                          "request": {
                                                                        "limit_size_in_bytes": 415550668,
                                                                        "limit_size": "396.2mb",
                                                                        "estimated_size_in_bytes": 16440,
                                                                        "estimated_size": "16kb",
                                                                        "overhead": 1.0,
                                                                        "tripped": 0
                                                          },
                                                          "parent": {
                                                                        "limit_size_in_bytes": 727213670,
                                                                        "limit_size": "693.5mb",
                                                                        "estimated_size_in_bytes": 29108992,
                                                                        "estimated_size": "27.7mb",
                                                                        "overhead": 1.0,
                                                                        "tripped": 0
                                                          }
                                           }
                             }
              }
}
```

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/blob/master/python.d/elasticsearch.chart.py#L441-L443

```python
        if 'open_file_descriptors' in to_netdata and 'max_file_descriptors' in to_netdata:
            to_netdata['file_descriptors_used'] = round(float(to_netdata['open_file_descriptors'])
                                                        / to_netdata['max_file_descriptors'] * 1000)

```

**Comment by ktsaou** [comment]
that fixes it of course.
