### ISSUE TITLE
mysql stats not reported by netdata after installation

### ISSUE THREAD

**Issue by fsantiago07044** [firehol/netdata#3087]
centos 7.4
mariadb 10.2
netdata served by nginx 1.13.7

i used the automated cli scripted install method. it works great. i have since created the mysql netdata user as specified in the mysql.conf file for the netdata plugin. After restarts, it still doesn't show up in netdata. i repeated the steps on another server and it worked fine there and i see mysql stats. the only difference between the two servers is the 2nd server uses apache instead of nginx. 

where else can i look for the issue to this?

**Comment by l2isbad** [comment]
Please run `mysql` plugin in debug mode as netdata user
https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins

**Comment by fsantiago07044** [comment]
December 1, 2017 10:23 AM, "Ilya Mashchenko" <notifications@github.com> wrote:

> Please run mysql plugin in debug mode as netdata user
> https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


2017-12-01 14:09:12: python.d INFO: plugin: main: Using python 2
2017-12-01 14:09:12: python.d DEBUG: plugin: main: module load source: 'mysql' => [OK]
2017-12-01 14:09:12: python.d DEBUG: plugin: main: module load config: 'mysql' => [OK]
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql mycnf1' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql mycnf2' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql debiancnf' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket1' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket2' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket3' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket4' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql tcp' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql tcpipv4' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql tcpipv6' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql mycnf1_root' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql mycnf2_root' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket1_root' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket2_root' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket3_root' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket4_root' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql tcp_root' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql tcpipv4_root' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql tcpipv6_root' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql mycnf1_netdata' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql mycnf2_netdata' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket1_netdata' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket2_netdata' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket3_netdata' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql socket4_netdata' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql tcp_netdata' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql tcpipv4_netdata' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: job initialization: 'mysql tcpipv6_netdata' => ['OK']
2017-12-01 14:09:12: python.d DEBUG: plugin: main: module status: 'mysql' => [OK] (jobs: 28)
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: debiancnf: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: debiancnf: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: debiancnf: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: debiancnf: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket1: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket1: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket1: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket1: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket2: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket2: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket2: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket2: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket3: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket3: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket3: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket3: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket4: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket4: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket4: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket4: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcp: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: tcp: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcp: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: tcp: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1_root: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1_root: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2_root: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2_root: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket1_root: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket1_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket1_root: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket1_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket2_root: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket2_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket2_root: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket2_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket3_root: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket3_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket3_root: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket3_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket4_root: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket4_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket4_root: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket4_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcp_root: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: tcp_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcp_root: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: tcp_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4_root: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4_root: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6_root: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6_root: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6_root: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1_netdata: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1_netdata: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf1_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2_netdata: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2_netdata: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: mycnf2_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket1_netdata: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket1_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket1_netdata: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket1_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket2_netdata: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket2_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket2_netdata: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket2_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket3_netdata: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket3_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket3_netdata: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket3_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket4_netdata: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: socket4_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: socket4_netdata: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: socket4_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcp_netdata: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: tcp_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcp_netdata: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: tcp_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4_netdata: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4_netdata: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv4_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6_netdata: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6_netdata: check() => [FAILED]
2017-12-01 14:09:12: python.d ERROR: mysql: tcpipv6_netdata: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-01 14:09:12: python.d INFO: plugin: main: FINISHED
bash-4.2$


--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC

**Comment by l2isbad** [comment]
`MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin`
^^
you have to install `mysql-python`

**Comment by fsantiago07044** [comment]
On December 1, 2017 10:39:57 PM EST, Ilya Mashchenko <notifications@github.com> wrote:
>`MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin`
>^^
>you have to install `mysql-python`

thank you. Got it and working. Case closed. 
--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC
