### ISSUE TITLE
Monitoring Samba

### ISSUE THREAD

**Issue by hornjt75862** [firehol/netdata#3197]
Trying to add the FileServe Samba and the error file is coming up with:
2017-12-30 13:35:29: python.d ERROR: samba: samba: Sorry, user netdata may not run sudo on HornPi.

2017-12-30 13:35:29: python.d ERROR: samba: samba: check() => [FAILED]

I would guess there might need to be more configuration then the samba.conf file, but not sure where to look.

**Comment by ktsaou** [comment]
Check this: https://github.com/firehol/netdata/tree/master/python.d#samba

You need to allow user netdata to run `smbstatus` as root. That page states the configuration needed.

**Comment by hornjt75862** [comment]
Getting closer. Here is testing the module:
netdata@HornPi:/home/pi$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace samba
2017-12-31 13:33:16: python.d INFO: plugin: main: Using python 2
2017-12-31 13:33:16: python.d DEBUG: plugin: main: module load source: 'samba' => [OK]
2017-12-31 13:33:16: python.d DEBUG: plugin: main: module load config: 'samba' => [OK]
2017-12-31 13:33:16: python.d DEBUG: plugin: main: job initialization: 'samba samba' => ['OK']
2017-12-31 13:33:16: python.d DEBUG: plugin: main: module status: 'samba' => [OK] (jobs: 1)
2017-12-31 13:33:16: python.d ERROR: samba: samba: Command "['/usr/bin/sudo', '-n', '/usr/bin/smbstatus', '-P']" returned no data
2017-12-31 13:33:16: python.d ERROR: samba: samba: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-31 13:33:16: python.d ERROR: samba: samba: check() => [FAILED]
2017-12-31 13:33:16: python.d ERROR: samba: samba: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2017-12-31 13:33:16: python.d INFO: plugin: main: FINISHED

**Comment by ktsaou** [comment]
Check this:

```
2017-12-31 13:33:16: python.d ERROR: samba: samba: Command "['/usr/bin/sudo', '-n', '/usr/bin/smbstatus', '-P']" returned no data
```

If you run `sudo smbstatus  -P` does it output anything? If not, probably you samba is not compiled with performance metrics in it.

**Comment by ktsaou** [comment]
I am closing this, but if there is something pending, post here and I'll reopen it.
