### ISSUE TITLE
debug snmp error

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [firehol/netdata#3210]
Hi,
    I use. / configure -- prefix = / opt/websuite/netdata - sysconfdir = / opt/config/netdata netdata installation, when I use the/opt/websuite/netdata/libexec/netdata/plugins. D/node. D.p lugin debug 1 SNMP times wrong, wrong is as follows:
2018-01-03 18:40:19: node.d.plugin: ERROR: Cannot read configuration file /opt/websuite/netdata/libexec/netdata/plugins.d/../../../../etc/netdata/node.d.conf: ENOENT, no such file or directory '/opt/websuite/netdata/libexec/netdata/plugins.d/../../../../etc/netdata/node.d.conf', using internal defaults.
2018-01-03 18:40:19: node.d.plugin: DEBUG: DEBUG enabled
2018-01-03 18:40:19: node.d.plugin: DEBUG: PARAM: 1
2018-01-03 18:40:19: node.d.plugin: DEBUG: Update frequency set to 1 seconds
2018-01-03 18:40:19: node.d.plugin: DEBUG: PARAM: snmp
2018-01-03 18:40:19: node.d.plugin: DEBUG: enabled module snmp
2018-01-03 18:40:19: node.d.plugin: DEBUG: loading module /opt/websuite/netdata/libexec/netdata/plugins.d/../node.d/snmp.node.js
2018-01-03 18:40:19: node.d.plugin: DEBUG: loaded
2018-01-03 18:40:19: node.d.plugin: DEBUG: loaded module snmp from /opt/websuite/netdata/libexec/netdata/plugins.d/../node.d/snmp.node.js
2018-01-03 18:40:19: node.d.plugin: DEBUG: loading module's snmp config /opt/websuite/netdata/libexec/netdata/plugins.d/../../../../etc/netdata/node.d/snmp.conf
2018-01-03 18:40:19: node.d.plugin: ERROR: Cannot load module's snmp config from /opt/websuite/netdata/libexec/netdata/plugins.d/../../../../etc/netdata/node.d/snmp.conf exception: Error: ENOENT, no such file or directory '/opt/websuite/netdata/libexec/netdata/plugins.d/../../../../etc/netdata/node.d/snmp.conf', using internal defaults.
2018-01-03 18:40:19: node.d.plugin: DEBUG: Error: ENOENT, no such file or directory '/opt/websuite/netdata/libexec/netdata/plugins.d/../../../../etc/netdata/node.d/snmp.conf'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at findModules (/opt/websuite/netdata/libexec/netdata/plugins.d/node.d.plugin:233:44)
    at Object.<anonymous> (/opt/websuite/netdata/libexec/netdata/plugins.d/node.d.plugin:271:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
2018-01-03 18:40:19: node.d.plugin: DEBUG: Configuring module snmp
2018-01-03 18:40:19: node.d.plugin: DEBUG: snmp: configuring (update_every: 1)...
2018-01-03 18:40:19: node.d.plugin: DEBUG: snmp: configured, reporting 0 eligible services.
2018-01-03 18:40:19: node.d.plugin: DEBUG: snmp: configuration finish callback called from configure().
2018-01-03 18:40:19: node.d.plugin: DEBUG: Configured module snmp
2018-01-03 18:40:19: node.d.plugin: DEBUG: Configuring module snmp reports 0 eligible services.
2018-01-03 18:40:19: node.d.plugin: DEBUG: started, services: []
DISABLE

**Comment by ktsaou** [comment]
Yes, this happens when the config directory is outside the installation directory and you run the plugin by hand.

You have 2 options:

1. export `NETDATA_CONFIG_DIR="/opt/config/netdata"`, or
2. `ln -s /opt/config/netdata /opt/websuite/netdata/etc/netdata`

**Comment by FANGXIANGQUAN** [comment]
Thank you very much. Your method has helped me to solve this problem.
