### ISSUE TITLE
mongodb authentication database

### ISSUE THREAD

**Issue by ikerfp** [firehol/netdata#3252]
Hello, I can't login to mongodb.

[root@mng ~]# /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mongodb
2018-01-09 21:11:40: python.d INFO: plugin: main: Using python 2
2018-01-09 21:11:40: python.d DEBUG: plugin: main: module load source: 'mongodb' => [OK]
2018-01-09 21:11:40: python.d DEBUG: plugin: main: module load config: 'mongodb' => [OK]
2018-01-09 21:11:40: python.d DEBUG: plugin: main: job initialization: 'mongodb local' => ['OK']
2018-01-09 21:11:40: python.d DEBUG: plugin: main: module status: 'mongodb' => [OK] (jobs: 1)
2018-01-09 21:11:40: python.d ERROR: mongodb: local: command SON([('authenticate', 1), ('user', u'admin'), ('nonce', u'XXXXXXXXXX'), ('key', u'XXXXXXXXXX')]) failed: auth failed
2018-01-09 21:11:40: python.d ERROR: mongodb: local: check() => [FAILED]
2018-01-09 21:11:40: python.d INFO: plugin: main: FINISHED

I have to add "--authenticationDatabase" admin when I want to connect to my mongodb server. So, I suppose that it would be necessary to add this parameter to .conf file

**Comment by l2isbad** [comment]
Hi @ikerfp 
I am not a mongodb user so i need your help.

I see

```
  - `source` (optional): the database to authenticate on. If not
    specified the current database is used.
```

Can you change
https://github.com/firehol/netdata/blob/master/python.d/mongodb.chart.py#L656

to (replace `DB_NAME' with your database name where credentials are stored)
```python
connection.admin.authenticate(name=self.user, password=self.password, source='DB_NAME')
```

If it works i will add a new option to the module configuration file.

**Comment by ikerfp** [comment]
I did this:
[root@mng ~]# nano /usr/libexec/netdata/python.d/mongodb.chart.py
change this

> connection.admin.authenticate(name=self.user, password=self.password)


by this

> connection.admin.authenticate(name=self.user, password=self.password, source='admin')


[root@mng ~]# service netdata restart
[root@mng ~]# /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mongodb
2018-01-10 11:56:40: python.d ERROR: mongodb: local: command SON([('authenticate', 1), ('user', u'admin'), ('nonce', u'fa26890b2870070d'), ('key', u'c3557f955fd6971c248b05b13ec32890')]) failed: auth failed

:(

**Comment by l2isbad** [comment]
Well, to be honest i don't know what the problem is 😢 

It is RHEL, isn't it? (it's always RHEL 😄 )

`mongodb, pymongo` versions?

I need to reproduce it somehow.

What i did:
1. Install mongodb on debian9 (3.2.11-2+deb9u1)
2. 
```
use admin
db.createUser(
  {
    user: "myUserAdmin",
    pwd: "abc123",
    roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
  }
)
```

3. Connect to the database from shell
`mongo -u myUserAdmin -p abc123 --authenticationDatabase admin`

It works.

**Comment by ikerfp** [comment]
CentOS 7 hehe
mongodb v3.4.10
pymongo v2.5.2-4

I can connect from the shell like you

**Comment by l2isbad** [comment]
Did you install pymongo from repo?
I suggest to remove it and install it by `pip` (newer version)

> I can connect from the shell like you

You can try it from python interpreter

python

```python
import pymongo
conn = pymongo.MongoClient()
# source='admin' is the default...
connection.admin.authenticate(name='myUserAdmin', password='abc123')

```

That is what module do.

**Comment by ikerfp** [comment]
Now is working!! Thanks a lot

```
# yum remove python-pymongo
# pip install pymongo
 
# /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mongodb
```
> 2018-01-10 13:36:07: python.d INFO: plugin: main: Using python 2
> 2018-01-10 13:36:07: python.d DEBUG: plugin: main: module load source: 'mongodb' => [OK]
> 2018-01-10 13:36:07: python.d DEBUG: plugin: main: module load config: 'mongodb' => [OK]
> 2018-01-10 13:36:07: python.d DEBUG: plugin: main: job initialization: 'mongodb local' => ['OK']
> 2018-01-10 13:36:07: python.d DEBUG: plugin: main: module status: 'mongodb' => [OK] (jobs: 1)
> 2018-01-10 13:36:07: python.d INFO: mongodb: local: check() => [OK]
> CHART netdata.runtime_mongodb_local '' 'Execution time for mongodb_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
> DIMENSION run_time 'run time' absolute 1 1
> 
> 2018-01-10 13:36:07: python.d DEBUG: mongodb: local: create() => [OK] (charts: 27)
> 2018-01-10 13:36:07: python.d DEBUG: mongodb: local: started, update frequency: 1, retries: 60
> 2018-01-10 13:36:07: python.d DEBUG: mongodb: local: sleeping for 0.595465898514 to reach frequency of 1 sec

**Comment by ne0c0de** [comment]
Hi,

I'm trying to configure MongoDB plugin 

Enabled pymongo package, configuration is ok but when i run the command `/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug mongodb` this is the result:

```
2018-01-30 09:16:47:  INFO: Using python v2
2018-01-30 09:16:48:  INFO: YAML output is ordered
2018-01-30 09:16:48: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2018-01-30 09:16:48: python.d INFO: MODULES_DIR='/usr/libexec/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['mongodb']
2018-01-30 09:16:48: python.d DEBUG: mongodb: loading module configuration: '/etc/netdata/python.d/mongodb.conf'
2018-01-30 09:16:48: python.d DEBUG: mongodb: reading configuration
2018-01-30 09:16:48: python.d DEBUG: mongodb/azurefb: job added
2018-01-30 09:16:48: python.d DEBUG: all job objects [<Service(azurefb, initial daemon)>]
2018-01-30 09:16:48: python.d ERROR: mongodb_azurefb No servers found yet
2018-01-30 09:16:48: python.d ERROR: mongodb_azurefb check() failed - disabling job
2018-01-30 09:16:48: python.d ERROR: DISABLED: mongodb/azurefb
2018-01-30 09:16:48: python.d DEBUG: overridden job names: []
2018-01-30 09:16:48: python.d DEBUG: all remaining job objects: []
2018-01-30 09:16:49: python.d FATAL: no more jobs
DISABLE
```

Am i doing something wrong? ( i'm able to connect mongodb server ip over 27017 via telnet)

**Comment by ktsaou** [comment]
hm... this message is not very helpful. @l2isbad any ideas what could be wrong?

**Comment by l2isbad** [comment]
@ktsaou 
discussion in https://github.com/firehol/netdata/issues/3366

**Comment by ktsaou** [comment]
oops! sorry! (too many issues)

**Comment by aadityabagga** [comment]
I am facing this issue too...

As per https://github.com/firehol/netdata/issues/3252#issuecomment-356588814

~~~~
import pymongo
conn = pymongo.MongoClient()
# source='admin' is the default...
conn.admin.authenticate(name='myUserAdmin', password='abc123')
~~~~

gives error
~~~~
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 1274, in authenticate
    connect=True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 614, in _cache_credentials
    sock_info.authenticate(credentials)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 688, in authenticate
    auth.authenticate(credentials, self)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 563, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 540, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 262, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.
~~~~

using same credentials via mongo command line client works:
~~~~
$ mongo -u 'myUserAdmin' -p 'abc123'
MongoDB shell version v3.4.10
connecting to: mongodb://127.0.0.1:27017
MongoDB server version: 3.4.10
> 
~~~~

**Comment by aadityabagga** [comment]
Authentication is working for me now with **netdata v1.11**
