### ISSUE TITLE
Problems connecting to MariaDB

### ISSUE THREAD

**Issue by badarotti** [firehol/netdata#3263]
Hi,
I'm having problems connecting netdata to MariaDB on openSUSE 42.3. I have python-PyMySQL installed and created the netdata user in MariaDB with usage and replication client privileges. I tried both with and without password in the DB. Here's the configuration and plugin debug info run as the host netdata user.

I would appreciate all the help.
Thank you.

mysql.conf
`MariaDB:
name: 'MariaDB'
user: 'netdata'
pass: 'password'
socket: '/var/run/mysql/mysql.sock'`

/usr/lib/netdata/plugins.d/python.d.plugin 1 debug trace mysql
```
2018-01-11 03:10:53: python.d INFO: plugin: main: Using python 2
2018-01-11 03:10:53: python.d DEBUG: plugin: main: module load source: 'mysql' => [OK]
2018-01-11 03:10:53: python.d ERROR: plugin: main: module load config: 'mysql' => [FAILED]
2018-01-11 03:10:53: python.d ERROR: plugin: main: Traceback (most recent call last):
  File "/usr/lib/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2018-01-11 03:10:53: python.d ERROR: plugin: main: load config error : [Errno 13] Permission denied: '/usr/lib/netdata/plugins.d/../../../../etc/netdata/python.d/mysql.conf'
2018-01-11 03:10:53: python.d ERROR: plugin: main: Traceback (most recent call last):
  File "/usr/lib/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2018-01-11 03:10:53: python.d DEBUG: plugin: main: job initialization: 'mysql mysql' => ['OK']
2018-01-11 03:10:53: python.d DEBUG: plugin: main: module status: 'mysql' => [OK] (jobs: 1)
2018-01-11 03:10:53: python.d ERROR: mysql: mysql: Connection properties are missing
2018-01-11 03:10:53: python.d ERROR: mysql: mysql: Traceback (most recent call last):
  File "/usr/lib/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2018-01-11 03:10:53: python.d ERROR: mysql: mysql: check() => [FAILED]
2018-01-11 03:10:53: python.d ERROR: mysql: mysql: Traceback (most recent call last):
  File "/usr/lib/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2018-01-11 03:10:53: python.d INFO: plugin: main: FINISHED
```

**Comment by l2isbad** [comment]
> 2018-01-11 03:10:53: python.d ERROR: plugin: main: load config error : [Errno 13] Permission denied: '/usr/lib/netdata/plugins.d/../../../../etc/netdata/python.d/mysql.conf'

^^
please run `python.d.plugin` as `netdata` user

**Comment by ktsaou** [comment]
Closing due to inactivity.
Feel free to post if the issue remains.
