### ISSUE TITLE
postfix plugin fail to get data from the postqueue command

### ISSUE THREAD

**Issue by nicolasbadia** [firehol/netdata#3406]
Since a few days, I do not have my postfix chart anymore.
I get this error in the log:
    
    python.d ERROR: postfix: local: Command "['/usr/sbin/postqueue', '-p']" returned no data

But if I run:

    su -s /bin/bash netdata
    /usr/sbin/postqueue -p

I do get content:

```
-Queue ID-  --Size-- ----Arrival Time---- -Sender/Recipient-------
EA7EE3C0EBA     6318 Fri Feb  9 01:57:40  “SecretIngredient”@***.win

42C743C2181     4679 Sat Feb 10 06:41:33  MAILER-DAEMON
(connect to ***.net[***.***.135.199]:25: Connection refused)
                                         Egufyn@***.net

-- 10 Kbytes in 2 Requests.
```

Any idea on what is going on and how to debug this?
I tried to reinstall netdata but I doesn't change anything.

**Comment by l2isbad** [comment]
Hi @nicolasbadia 

```bash
# become user netdata
sudo su -s /bin/bash netdata

# execute the plugin in debug mode, for a specific module.
# example for the python plugin, mysql module:
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace postfix
```

**Comment by nicolasbadia** [comment]
Thanks a lot for the quick answer.
Unfortunatly, it doesn't help much...
This give me:

```
2018-02-12 11:10:19: python.d INFO: plugin: main: Using python 2
2018-02-12 11:10:19: python.d DEBUG: plugin: main: module load source: 'postfix' => [OK]
2018-02-12 11:10:19: python.d DEBUG: plugin: main: module load config: 'postfix' => [OK]
2018-02-12 11:10:19: python.d DEBUG: plugin: main: job initialization: 'postfix local' => ['OK']
2018-02-12 11:10:19: python.d DEBUG: plugin: main: module status: 'postfix' => [OK] (jobs: 1)
2018-02-12 11:10:19: python.d ERROR: postfix: local: Can't locate "postqueue -p" binary
2018-02-12 11:10:19: python.d ERROR: postfix: local: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2018-02-12 11:10:19: python.d ERROR: postfix: local: check() => [FAILED]
2018-02-12 11:10:19: python.d ERROR: postfix: local: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2018-02-12 11:10:19: python.d INFO: plugin: main: FINISHED
```

If I change `postqueue -p` by `/usr/sbin/postqueue -p` in `postfix.conf`, I get this:

```
2018-02-12 11:12:55: python.d INFO: plugin: main: Using python 2
2018-02-12 11:12:55: python.d DEBUG: plugin: main: module load source: 'postfix' => [OK]
2018-02-12 11:12:55: python.d DEBUG: plugin: main: module load config: 'postfix' => [OK]
2018-02-12 11:12:55: python.d DEBUG: plugin: main: job initialization: 'postfix local' => ['OK']
2018-02-12 11:12:55: python.d DEBUG: plugin: main: module status: 'postfix' => [OK] (jobs: 1)
2018-02-12 11:12:55: python.d ERROR: postfix: local: Command "['/usr/sbin/postqueue', '-p']" returned no data
2018-02-12 11:12:55: python.d ERROR: postfix: local: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2018-02-12 11:12:55: python.d ERROR: postfix: local: check() => [FAILED]
2018-02-12 11:12:55: python.d ERROR: postfix: local: Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2018-02-12 11:12:55: python.d INFO: plugin: main: FINISHED
```

Which is basically the same issue as before without much more details to debug it.

The error `cannot import name monotonic` is not the problem as I tested this on another server with almost the same config (and where postfix works in netdata) which give me the same output when I run `/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace postfix`  (excepted for the line `2018-02-12 11:12:55: python.d ERROR: postfix: local: Command "['/usr/sbin/postqueue', '-p']" returned no data`)

**Comment by l2isbad** [comment]
Please do as `netdata` user in python interpreter (`exit()` to exit):

```python

from subprocess import Popen, PIPE

p = Popen(['/usr/sbin/postqueue', '-p'], stdout=PIPE, stderr=PIPE)

rv = list()
for line in p.stdout:
	rv.append(line.decode())
	

print(rv)

raw = rv[-1].split()

print(raw)

if not raw[0] == 'Main' and raw[1] == 'queue':
	print(raw[4], raw[1])
```

**Comment by nicolasbadia** [comment]
I created a python file `netdata_postfix_test.py` and here is what I get when I execute it:

```
Traceback (most recent call last):
  File "netdata_postfix_test.py", line 7, in <module>
    rv.append(line.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
```

**Comment by l2isbad** [comment]
@nicolasbadia script edited. try it one more time

**Comment by nicolasbadia** [comment]
I do get content this time:


> [u'-Queue ID-  --Size-- ----Arrival Time---- -Sender/Recipient-------\n', u'0E8613C17F5     2266 Sun Feb 11 13:26:11  root@***.com\n', u'          (connect to ***.com[***.95.228.241]:25: Connection timed out)\n', u'                                         root@***.com\n', u'\n', u'EA7EE3C0EBA     6318 Fri Feb  9 01:57:40  \u201cSecretIngredient\u201d@***.win\n', u'\n', u'C9DC63C0D4F     4437 Sun Feb 11 18:26:54  contact@***.fr\n', u'             (connect to mail.life.fr[***.222.225.35]:25: Connection timed out)\n', u'                                         fanny-***@life.fr\n', u'\n', u'-- 12 Kbytes in 3 Requests.\n']
> [u'--', u'12', u'Kbytes', u'in', u'3', u'Requests.']

**Comment by l2isbad** [comment]
i think it's fixed in https://github.com/firehol/netdata/pull/3413

can you test it?

**Comment by nicolasbadia** [comment]
It did fix the issue for me.
