### ISSUE TITLE
Error: MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin

### ISSUE THREAD

**Issue by jonathannz** [firehol/netdata#3428]
I gather my issue is the same as that posted here: https://github.com/firehol/netdata/issues/1588

I was also getting the error, `MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin`.

I installed `python-pip` package, and then did a `pip install PyMySQL` command, as per the instruction on that issue discussion. But I still get the same error.

I am not all that familiar with Python. Is there some command I must run to reload it after adding the `PyMySQL` module to it? I've searched online for information on such, but turned up nothing related to reloading Python.

Please advise.
Thanks.

**Comment by l2isbad** [comment]
a similar problem https://github.com/firehol/netdata/issues/3416

**Comment by jonathannz** [comment]
I also found issue https://github.com/firehol/netdata/issues/2514
I see that the PyMySQL module was available to Python 3.x but not 2.7
So I tried following the recommended procedure found [here](https://github.com/firehol/netdata/issues/1731#issuecomment-277767601).
The issue continues.

**Comment by jonathannz** [comment]
We cross posted. Now looking into #3416

**Comment by l2isbad** [comment]
what OS are you using?

MySQLdb is preferable

i see centos has `mysql-python` and debian has `python-mysqldb` package

**Comment by jonathannz** [comment]
I've been fiddling around with this MySQL issue for a few hours, and have yet to solve it.

Looking at $3416, I have no idea what my `PYTHONPATH` should be set to.
This is all relatively new to me. If someone could please walk me through how to potentially solve this, it would be much appreciated.

**Comment by jonathannz** [comment]
I am on Ubutnu 16.04
I went with PyMySQL simply because that's what I saw mentioned in #1588
Should I reverse all that I've tried so far, and install that deb package?

**Comment by l2isbad** [comment]
> and install that deb package?

why not

**Comment by jonathannz** [comment]
Okay. That was much easier than the past couple of hours led me to believe it would be. :-)
I installed `python-mysqldb` package, and it's up and running.
It might pay to add that to whatever documentation addresses configuring the MySQL DB plugin.
Thanks for the suggestion.
Should I both removing the various path changes, symbollic links, etc., I made whilst following the various above mentioned issue comments?

**Comment by l2isbad** [comment]
> Should I both removing the various path changes, symbollic links, etc., I made whilst following the various above mentioned issue comments?

i think yes

**Comment by jonathannz** [comment]
Thanks. Issue solved.

**Comment by mardoyyy** [comment]
previously i had the same problem
ubuntu 18.04
Netdata installed from wordops stack.

it was clean installed, eventhough mariadb and every mysql stuffs already installed, netdata can't recognized it.

here is my steps to resolved it
--become user netdata
**sudo su -s /bin/bash netdata**

--execute the plugin in debug mode, for a specific module.
--example for the python plugin, mysql module:
--Debug mysql netdata
**/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace mysql**

then I got these error messages

netdata@vps:/home/ubuntu$ /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace mysql
2020-03-24 11:07:26: python.d INFO: plugin[main] : **using python v2**
2020-03-24 11:07:26: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/opt/netdata/etc/netdata', '/opt/netdata/usr/lib/netdata/conf.d']
2020-03-24 11:07:26: python.d DEBUG: plugin[main] : loading '/opt/netdata/usr/lib/netdata/conf.d/python.d.conf'
2020-03-24 11:07:26: python.d DEBUG: plugin[main] : '/opt/netdata/usr/lib/netdata/conf.d/python.d.conf' is loaded
2020-03-24 11:07:26: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /opt/netdata/var/lib/netdata
2020-03-24 11:07:26: python.d DEBUG: plugin[main] : loading '/opt/netdata/var/lib/netdata/pythond-jobs-statuses.json'
2020-03-24 11:07:26: python.d DEBUG: plugin[main] : '/opt/netdata/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2020-03-24 11:07:26: python.d DEBUG: plugin[main] : [mysql] looking for 'mysql.conf' in ['/opt/netdata/etc/netdata/python.d', '/opt/netdata/usr/lib/netdata/conf.d/python.d']
2020-03-24 11:07:26: python.d DEBUG: plugin[main] : [mysql] loading '/opt/netdata/usr/lib/netdata/conf.d/python.d/mysql.conf'
2020-03-24 11:07:26: python.d DEBUG: plugin[main] : [mysql] '/opt/netdata/usr/lib/netdata/conf.d/python.d/mysql.conf' is loaded
2020-03-24 11:07:26: python.d INFO: plugin[main] : [mysql] built 28 job(s) configs
2020-03-24 11:07:26: python.d ERROR: mysql[mycnf1] : **MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin**
2020-03-24 11:07:26: python.d ERROR: mysql[mycnf1] : Traceback (most recent call last):
  File "/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue

2020-03-24 11:07:26: python.d INFO: plugin[main] : mysql[mycnf1] : check failed
2020-03-24 11:07:26: python.d ERROR: mysql[mycnf2] : MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2020-03-24 11:07:26: python.d ERROR: mysql[mycnf2] : Traceback (most recent call last):
  File "/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin", line 39, in <module>
    from queue import Queue
ImportError: No module named queue


after 4 hours install and re-install and even create new VM, it just solved by simply, install this
**sudo apt-get install python2.7-mysqldb**


Hope it help someone else :D

**Comment by dpointk** [comment]
on CentOs 6.10 I was missing `yum install MySQL-python`
