### ISSUE TITLE
MySQL didn't return data with netdata user

### ISSUE THREAD

**Issue by Cepxio** [firehol/netdata#3446]
Hi, 

I have installed netdata as indicated in the documentation, but it can't work with _netdata_ user as was indicated in the doc.
When I changed it for root user (all privileges), netdata service start ok and get metrics from MySQL.
If not, the debug trace mysql finish with errors:

```
netdata@mariadb:/$ /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace mysql
2018-02-20 14:09:55: python.d INFO: plugin: main: Using python 2
2018-02-20 14:09:55: python.d DEBUG: plugin: main: module load source: 'mysql' => [OK]
2018-02-20 14:09:55: python.d DEBUG: plugin: main: module load config: 'mysql' => [OK]
2018-02-20 14:09:55: python.d DEBUG: plugin: main: job initialization: 'mysql tcpipv4_netdata' => ['OK']
2018-02-20 14:09:55: python.d DEBUG: plugin: main: module status: 'mysql' => [OK] (jobs: 1)
2018-02-20 14:09:56: python.d ERROR: mysql: tcpipv4_netdata: _get_data() returned no data or type is not <dict>
2018-02-20 14:09:56: python.d ERROR: mysql: tcpipv4_netdata: Traceback (most recent call last):
  File "/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2018-02-20 14:09:56: python.d ERROR: mysql: tcpipv4_netdata: check() => [FAILED]
2018-02-20 14:09:56: python.d ERROR: mysql: tcpipv4_netdata: Traceback (most recent call last):
  File "/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin", line 19, in <module>
    from time import monotonic as time
ImportError: cannot import name monotonic

2018-02-20 14:09:56: python.d INFO: plugin: main: FINISHED
``` 
System info:

- Ubuntu 16.04.3 LTS 
- Python 2.7.12
- pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
- mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- The GRANT statement was taken from /opt/netdata/netdata-configs/python.d/mysql.conf

```
# > create user 'netdata'@'localhost';
# > grant usage on *.* to 'netdata'@'localhost' with grant option;
# > flush privileges;
```
Run Netdata debug trace mysql with MySQL root user:

```
netdata@mariadb-social-00:/root$ /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 2 debug trace mysql
2018-02-20 14:58:46: python.d INFO: plugin: main: Using python 2
2018-02-20 14:58:46: python.d DEBUG: plugin: main: module load source: 'mysql' => [OK]
2018-02-20 14:58:46: python.d DEBUG: plugin: main: module load config: 'mysql' => [OK]
2018-02-20 14:58:46: python.d DEBUG: plugin: main: job initialization: 'mysql tcpipv4_netdata' => ['OK']
2018-02-20 14:58:46: python.d DEBUG: plugin: main: module status: 'mysql' => [OK] (jobs: 1)
2018-02-20 14:58:46: python.d INFO: mysql: tcpipv4_netdata: check() => [OK]
CHART netdata.runtime_mysql_local '' 'Execution time for mysql_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 2
DIMENSION run_time 'run time' absolute 1 1

2018-02-20 14:58:46: python.d DEBUG: mysql: tcpipv4_netdata: create() => [OK] (charts: 42)
2018-02-20 14:58:46: python.d DEBUG: mysql: tcpipv4_netdata: started, update frequency: 2, retries: 60
2018-02-20 14:58:46: python.d DEBUG: mysql: tcpipv4_netdata: sleeping for 1.53556990623 to reach frequency of 2 sec
CHART mysql_local.join_issues '' 'mysql Select Join Issues' 'joins/s' 'issues' 'mysql.join_issues' line 60004 2 '' 'python.d.plugin' 'mysql'
DIMENSION 'Select_full_join' 'full_join' incremental 1 1 ''
DIMENSION 'Select_full_range_join' 'full_range_join' incremental 1 1 ''
DIMENSION 'Select_range' 'range' incremental 1 1 ''
DIMENSION 'Select_range_check' 'range_check' incremental 1 1 ''
DIMENSION 'Select_scan' 'scan' incremental 1 1 ''
.....
```

**Comment by l2isbad** [comment]
hi @Cepxio

have  you solved it?
