### ISSUE TITLE
Icecast module not working

### ISSUE THREAD

**Issue by tommybuck** [firehol/netdata#3715]
2018-05-11 12:46:15: python.d INFO: plugin: main: Using python 2
2018-05-11 12:46:15: python.d DEBUG: plugin: main: module load source: 'icecast' => [OK]
2018-05-11 12:46:15: python.d DEBUG: plugin: main: module load config: 'icecast' => [OK]
2018-05-11 12:46:15: python.d DEBUG: plugin: main: job initialization: 'icecast localhost' => ['OK']
2018-05-11 12:46:15: python.d DEBUG: plugin: main: job initialization: 'icecast localipv4' => ['OK']
2018-05-11 12:46:15: python.d DEBUG: plugin: main: module status: 'icecast' => [OK] (jobs: 2)
2018-05-11 12:46:15: python.d ERROR: icecast: localhost: check() unhandled exception: 'unicode' object has no attribute 'get'
2018-05-11 12:46:15: python.d INFO: icecast: localhost: check() => [FAILED]
2018-05-11 12:46:15: python.d ERROR: icecast: localipv4: check() unhandled exception: 'unicode' object has no attribute 'get'
2018-05-11 12:46:15: python.d INFO: icecast: localipv4: check() => [FAILED]
2018-05-11 12:46:15: python.d INFO: plugin: main: FINISHED

**Comment by l2isbad** [comment]
please run

`netdata@webserver:/$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug icecast trace`

i checked and it works for me for both py2 and py3.  Used this [link](http://192.99.34.205:8443/status-json.xsl) for test.

**Comment by tommybuck** [comment]
2018-05-11 13:07:59: python.d INFO: plugin: main: Using python 2
2018-05-11 13:08:00: python.d DEBUG: plugin: main: module load source: 'icecast' => [OK]
2018-05-11 13:08:00: python.d DEBUG: plugin: main: module load config: 'icecast' => [OK]
2018-05-11 13:08:00: python.d DEBUG: plugin: main: job initialization: 'icecast localhost' => ['OK']
2018-05-11 13:08:00: python.d DEBUG: plugin: main: job initialization: 'icecast localipv4' => ['OK']
2018-05-11 13:08:00: python.d DEBUG: plugin: main: module status: 'icecast' => [OK] (jobs: 2)
2018-05-11 13:08:02: python.d ERROR: icecast: localhost: Url: http://192.168.3.2:8000/status-json.xsl. Error: HTTPConnectionPool(host='192.168.3.2', port=8000): Max retries exceeded with url: /status-json.xsl (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x76554070>, 'Connection to 192.168.3.2 timed out. (connect timeout=1)'))
2018-05-11 13:08:02: python.d ERROR: icecast: localhost: Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 94, in _get_raw_data
    status, data = self._get_raw_data_with_status(url, manager)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 117, in _get_raw_data_with_status
    redirect=redirect)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPConnectionPool(host='192.168.3.2', port=8000): Max retries exceeded with url: /status-json.xsl (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x76554070>, 'Connection to 192.168.3.2 timed out. (connect timeout=1)'))

2018-05-11 13:08:02: python.d INFO: icecast: localhost: check() => [FAILED]
2018-05-11 13:08:04: python.d ERROR: icecast: localipv4: Url: http://192.168.3.2:8000/status-json.xsl. Error: HTTPConnectionPool(host='192.168.3.2', port=8000): Max retries exceeded with url: /status-json.xsl (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x765545d0>, 'Connection to 192.168.3.2 timed out. (connect timeout=1)'))
2018-05-11 13:08:04: python.d ERROR: icecast: localipv4: Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 94, in _get_raw_data
    status, data = self._get_raw_data_with_status(url, manager)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 117, in _get_raw_data_with_status
    redirect=redirect)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPConnectionPool(host='192.168.3.2', port=8000): Max retries exceeded with url: /status-json.xsl (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x765545d0>, 'Connection to 192.168.3.2 timed out. (connect timeout=1)'))

2018-05-11 13:08:04: python.d INFO: icecast: localipv4: check() => [FAILED]
2018-05-11 13:08:04: python.d INFO: plugin: main: FINISHED


Think it could be my firewall blocking the connection?

**Comment by l2isbad** [comment]
> Think it could be my firewall blocking the connection?

It could. I see http `ConnectTimeoutError`

**Comment by ktsaou** [comment]
Closing due to inactivity.
Feel free to post if the issue remains.

**Comment by tommybuck** [comment]
Hi,
 
Finally got round to sorting out my firewall. However the original issue still remains. I have figured out the issue though I think.

The test server you have been using has multiple source arrays in the json.
[http://192.99.34.205:8443/status-json.xsl](url)
![image](https://user-images.githubusercontent.com/22301046/47145344-67fdaf80-d2c1-11e8-86f9-91ff6e505ad0.png)

Where as mine doesnt have any source arrays just the data.
![image](https://user-images.githubusercontent.com/22301046/47145555-e9edd880-d2c1-11e8-9cfb-49b80129a5e3.png)

Can you take another look please?

**Comment by l2isbad** [comment]
Pleaso open new issue

**Comment by E46-S54** [comment]
@tommybuck - I am having issues with with this plugin, are you using the standard xml2json.xslt and status-json.xsl files for Icecast? Which version are you using 

Thanks

**Comment by tommybuck** [comment]
Icecast 2.4.2

And status-json.xsl

**Comment by ilyam8** [comment]
> I am having issues with with this plugin

i see in req we have

> icecast version >= 2.4.0


What version are you using @E46-S54?  And please share your `/status-json.xsl` like in [this comment](https://github.com/netdata/netdata/issues/3715#issuecomment-430943917)
