### ISSUE TITLE
varnish 5 support

### ISSUE THREAD

**Issue by benwh4** [firehol/netdata#4073]
Hello, 

When I try to launch : `/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace varnish  ` as netdata user, I run into this error ...
```shell
2018-08-23 11:15:45: python.d ERROR: varnish: job_name: update() unhandled exception: 's0.g_bytes'
2018-08-23 11:15:45: python.d ERROR: varnish: job_name: Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 185, in run
    updated = self.update(interval=job.SINCE_UPDATE)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 211, in update
    data = self.get_data()
  File "/usr/libexec/netdata/python.d/varnish.chart.py", line 217, in get_data
    data['memory_allocated'] = data['s0.g_bytes']
KeyError: 's0.g_bytes'
```

I don't know if I can ignore this in the configuration file.

What can I do to have my varnish charts ?

**Comment by benwh4** [comment]
I have those value in my varnishstat : 
```shell
  "SMA.default.g_bytes": {
    "description": "Bytes outstanding",
    "type": "SMA", "ident": "default", "flag": "g", "format": "B",
    "value": 70497863
  },
  "SMA.default.g_space": {                                                                                                                                                                                                                              
    "description": "Bytes available",
    "type": "SMA", "ident": "default", "flag": "g", "format": "B",
    "value": 8519436729
  },
```

I run `varnishd (varnish-5.0.0 revision 99d036f)` and is it possible to modify those values : 
```python
        data['memory_allocated'] = data['s0.g_bytes']
        data['memory_free'] = data['s0.g_space']

return data
```

in  python.d/varnish.chart.py ?

**Comment by gilwi** [comment]
Hello, 

I tried `print data` right after the following line:
``` data.update(dict((param, value) for _, param, value in server_stats)) ```

It seems the values in are labeled "default.g_bytes" and "default.g_space".

Can you try this:
```
data['memory_allocated'] = data['default.g_bytes']
data['memory_free'] = data['default.g_space']
```

Hope it'll help

**Comment by benwh4** [comment]
Yes !! I modify the file varnish.chart.py with default as the print data return : 
```shell
2018-08-23 12:53:56: python.d DEBUG: varnish: job_name: update => [FAILED] (elapsed time: -, retries left: 57)
2018-08-23 12:53:56: python.d DEBUG: varnish: job_name: sleeping for 0.990350470878 to reach frequency of 1 sec
{u'sc_pipe_overflow': u'0', u's_pipe_out': u'1500', u's_pass': u'13755', u's_pipe_hdrbytes': u'1271', u'sc_req_close': u'188', u'vsm_free': u'973680', u'exp_mailed': u'25413', u'fetch_chunked': u'20385', u'default.c_bytes': u'507232709', u'sess_que
ued': u'0', u'fetch_204': u'0', u'exp_received': u'25413', u'default.c_fail': u'0', u'to': u'417', u'wq.creat': u'3', u'lru.destroy': u'0', u'busyobj.pool': u'10', u'backend.destroy': u'0', u'pipestat.creat': u'1', u'cli.creat': u'1', u'n_vampireob
ject': u'0', u'busy_sleep': u'8', u'sess1.frees': u'1191782', u'exp.creat': u'1', u'fetch_eof': u'0', u'n_vcl_avail': u'1', u'req1.randry': u'0', u'n_expired': u'5800', u'a*******1_beresp_hdrbytes': u'16289731', u'backend_req': u'30778', u'req1.rec
ycle': u'1209501', u'n_objecthead': u'2880', u'client_req_400': u'0', u'objhdr.creat': u'7641', u'child_start': u'1', u's_synth': u'20', u'sess0.timeout': u'6359', u'req1.sz_actual': u'65504', u'threads_limited': u'0', u'backend_unhealthy': u'4', u
'mempool.destroy': u'0', u'bans_tests_tested': u'11909266', u'sess_drop': u'0', u'busyobj.destroy': u'36603', u'waiter.locks': u'344831', u'exp.destroy': u'0', u'bans_obj_killed': u'8252', u'sess_fail': u'0', u'req0.recycle': u'1207653', u'vsm_over
flow': u'0', u'busyobj.frees': u'30791', u'busyobj.randry': u'21', u'boot.a*******1.happy': u'18446744073709551615', u'backend.creat': u'3', u'hcb_insert': u'7611', u'boot.a*******1.conn': u'0', u'boot.a*******1.beresp_bodybytes': u'396078457', u'n
_gzip': u'0', u'bans_lurker_obj_killed': u'0', u'threads': u'400', u'default.g_space': u'8517958769', u'mempool.locks': u'28105100', u'waiter.creat': u'2', u'pipestat.locks': u'4', u'backend_reuse': u'28018', u's_pipe_in': u'0', u'sess_closed': u'2
13', u'sess1.pool': u'10', u'sess0.pool': u'10', u'sess0.sz_wanted': u'512', u'child_stop': u'0', u'shm_records': u'202649760', u'child_panic': u'0', u'child_dump': u'0', u'bans_persisted_bytes': u'36984249', u'vsm_overflowed': u'0', u'fetch_head':
 u'0', u'vcl.locks': u'67762', u'sess.destroy': u'2383559', u'busyobj.locks': u'421640', u'vbe.creat': u'1', u'hcb.locks': u'35472', u'boot.a********1.beresp_hdrbytes': u'16289731', u'boot.a*******1.conn': u'0', u'vmods': u'2', u'wq.destroy': u'0',
 u'child_exit': u'0', u'Transient.g_bytes': u'0', u'boot.a*******1.pipe_in': u'1500', u'Transient.c_freed': u'281451914', u'busyobj.sz_wanted': u'65536', u'req1.surplus': u'0', u'sess.locks': u'2450935', u'n_lru_nuked': u'0', u'req1.sz_wanted': u'6
5536', u'boot.a********1.bereq_bodybytes': u'0', u'wstat.destroy': u'0', u'boot.a*******1.req': u'30785', u'sess_closed_err': u'9491', u'cache_hit': u'2360095', u'sess0.sz_actual': u'480', u'pipestat.destroy': u'0', u'fetch_failed': u'0', u'Transie
nt.g_alloc': u'0', u'n_vcl': u'1', u'sess1.allocs': u'1191782', u'Transient.c_bytes': u'281451914', u'vcl.destroy': u'0', u'shm_cont': u'6670', u'boot.a*******1.pipe_out': u'0', u'n_gunzip': u'2344304', u'a*******1_beresp_bodybytes': u'0', u's_fet
ch': u'30719', u'objhdr.locks': u'9850015', u'uptime': u'4158087', u'sess_readahead': u'0', u'shm_writes': u'17969532', u's_resp_bodybytes': u'932674180', u'ban.destroy': u'0', u'sess1.timeout': u'6286', u'esi_errors': u'0', u's_req': u'2390838', u
'sess1.recycle': u'1191782', u'sess1.surplus': u'0', u'req0.allocs': u'1207653', u'vsm_cooling': u'0', u'sess_conn': u'2383567', u'boot.a*******1.pipe_in': u'0', u'lru.locks': u'1232592', u'Transient.g_space': u'0', u'thread_queue_len': u'0', u'bo
ot.a*******1.beresp_hdrbytes': u'0', u'vxid.destroy': u'0', u'backend.locks': u'1170257', u'busyobj.surplus': u'0', u'sma.destroy': u'0', u'backend_busy': u'0', u'default.c_freed': u'435256886', u'Transient.c_fail': u'0', u'sc_tx_eof': u'0', u'ban
.creat': u'1', u'vbe.locks': u'1467358', u'sc_rx_bad': u'0', u'sc_resp_close': u'0', u'backend_conn': u'2767', u'hcb.destroy': u'0', u'sess0.allocs': u'1191785', u'bans_req': u'81500', u'hcb_lock': u'7611', u'sess1.randry': u'0', u'req1.allocs': u'
1209501', u'cli.destroy': u'0', u'sc_rx_overflow': u'0', u'client_req_417': u'0', u'bans_lurker_tests_tested': u'5258', u'cache_miss': u'16964', u'sess0.live': u'0', u'boot.a*******1.bereq_hdrbytes': u'30285140', u'n_obj_purged': u'0', u'req1.frees
': u'1209501', u'default.g_alloc': u'6300', u'child_died': u'0', u'bans': u'81532', u'boot.a********1.beresp_bodybytes': u'0', u'busyobj.allocs': u'30791', u'bans_tested': u'35789', u'boot.a*******1.bereq_bodybytes': u'40506267', u'req0.surplus': u
'0', u'threads_destroyed': u'0', u'req0.sz_actual': u'65504', u'cli.locks': u'1467365', u'backend_tcp.locks': u'120269', u'boot.a*******1.pipe_hdrbytes': u'0', u'sess0.frees': u'1191785', u'vcapace.destroy': u'0', u'fetch_bad': u'0', u'backend_fai
l': u'2', u's_pipe': u'4', u'backend_retry': u'2', u'pools': u'2', u'vsm_used': u'83960928', u'n_purges': u'0', u'bans_completed': u'36503', u'wq.locks': u'15374280', u'req0.toosmall': u'0', u's_req_bodybytes': u'40506267', u'fetch_length': u'10378
', u'busyobj.live': u'0', u'wstat.creat': u'1', u's_sess': u'2383567', u'n_vcl_discard': u'0', u'a*******1_beresp_bodybytes': u'396078457', u'backend_recycle': u'30682', u'busy_wakeup': u'8', u'objhdr.destroy': u'4760', u'fetch_none': u'0', u'req0.
frees': u'1207653', u'shm_flushes': u'102961', u'fetch_304': u'13', u'sc_rx_body': u'1', u'bans_dups': u'36544', u'sess1.toosmall': u'0', u'vxid.creat': u'1', u'wstat.locks': u'3056171', u'lru.creat': u'2', u'n_backend': u'2', u'sess0.surplus': u'0
', u'req0.timeout': u'4263', u'sc_rx_timeout': u'9473', u'backend_tcp.creat': u'2', u'sc_tx_pipe': u'4', u'bans_lurker_tested': u'5258', u'sess0.recycle': u'1191785', u'bans_deleted': u'77', u'client_req': u'2390838', u'req0.sz_wanted': u'65536', u
'boot.a********1.pipe_out': u'0', u'n_object': u'2851', u'cache_hitpass': u'0', u'boot.assppdbo1.pipe_hdrbytes': u'1439', u'bans_lurker_contention': u'0', u'sc_overload': u'0', u'req1.timeout': u'4551', u'Transient.c_req': u'51636', u'req0.pool': u
'10', u'sma.creat': u'2', u'sess0.toosmall': u'0', u'busyobj.toosmall': u'0', u'busyobj.creat': u'36624', u'ban.locks': u'672643', u'sess1.sz_wanted': u'512', u'sc_range_short': u'0', u'fetch_no_thread': u'0', u'threads_failed': u'0', u's_req_hdrby
tes': u'243335876', u'sess.creat': u'2383566', u'sma.locks': u'194556', u'default.g_bytes': u'71975823', u'sc_rem_close': u'2373878', u'vbe.destroy': u'0', u'waiter.destroy': u'0', u'vxid.locks': u'166', u'boot.a********1.bereq_hdrbytes': u'0', u'r
eq1.live': u'0', u'losthdr': u'0', u'busyobj.timeout': u'3761', u'shm_cycles': u'74', u'busy_killed': u'0', u'esi_warnings': u'0', u'assppdweb1_beresp_hdrbytes': u'0', u'boot.a*******1.happy': u'18446744073709551615', u'exp.locks': u'118266', u'n_
lru_moved': u'1201379', u'bans_obj': u'908', u'vcl.creat': u'1', u'sess0.randry': u'0', u'bans_persisted_fragmentation': u'17179151', u'mempool.creat': u'5', u'threads_created': u'400', u'sc_rx_junk': u'0', u'req0.randry': u'0', u'req1.toosmall': u
'0', u'vcapace.creat': u'1', u'req1.pool': u'10', u'bans_added': u'81609', u'sess1.sz_actual': u'480', u'busyobj.sz_actual': u'65504', u'sc_req_http10': u'17', u'req0.live': u'0', u'default.c_req': u'48792', u'sess1.live': u'0', u'hcb_nolock': u'23
77059', u'sc_tx_error': u'0', u's_resp_hdrbytes': u'1589913337', u'sess_dropped': u'0', u'sess_herd': u'43067', u'vcapace.locks': u'0', u'n_objectcore': u'2876', u'hcb.creat': u'1', u'boot.a********1.req': u'0', u'backend_tcp.destroy': u'0', u'busy
obj.recycle': u'30770', u'fetch_1xx': u'0'}
2018-08-23 12:53:57: python.d ERROR: varnish: job_name: update() unhandled exception: 'SMA.default.g_bytes'
2018-08-23 12:53:57: python.d ERROR: varnish: job_name: Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 185, in run
    updated = self.update(interval=job.SINCE_UPDATE)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/SimpleService.py", line 211, in update
    data = self.get_data()
  File "/usr/libexec/netdata/python.d/varnish.chart.py", line 220, in get_data
    data['memory_allocated'] = data['SMA.default.g_bytes']
KeyError: 'SMA.default.g_bytes'
```
I work now I think varnish 5 as different output from varnishstat

**Comment by ktsaou** [comment]
@l2isbad check this. Varnish 5 probably has different output. Can we support it?

**Comment by l2isbad** [comment]
`varnish 5.0.0-7+deb9u2`

```
sudo varnishstat -1 | grep _bytes
MAIN.bans_persisted_bytes               16          .   Bytes used by the persisted ban lists
SMA.s0.c_bytes                               0         0.00 Bytes allocated
SMA.s0.g_bytes                               0          .   Bytes outstanding
SMA.Transient.c_bytes                        0         0.00 Bytes allocated
SMA.Transient.g_bytes                        0          .   Bytes outstanding
```

post here your output from the same command @benwh4

**Comment by l2isbad** [comment]
> Logrotate screw me up every day I must modify the

that sucks, sorry for the delay, i made a PR with fix

**Comment by benwh4** [comment]
ok thanks

**Comment by benwh4** [comment]
Awesome fix thanks again
