### ISSUE TITLE
elasticsearch plugin python json exception if another service running on port 9200

### ISSUE THREAD

**Issue by thomas-pike** [firehol/netdata#4092]
We had a galera clustercheck service running on its default port of 9200. This understandably confused the elasticsearch plugin which checks the same port, but it actually caused a fatal error that caused all python.d plugins after it alphabetically to not load at all. The python exception looked like:
```Exception in thread Thread-118:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/x86_64-linux-gnu/netdata/python.d/elasticsearch.chart.py", line 402, in _get_cluste
    data = loads(raw_data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception in thread Thread-116:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/x86_64-linux-gnu/netdata/python.d/elasticsearch.chart.py", line 419, in _get_node_s
    data = loads(raw_data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception in thread Thread-117:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/x86_64-linux-gnu/netdata/python.d/elasticsearch.chart.py", line 380, in _get_cluste
    data = loads(raw_data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Probably the exception should be caught and handled in a more graceful way.

**Comment by ktsaou** [comment]
@l2isbad have a look at this please.

**Comment by l2isbad** [comment]
Ops, this is a bug @ktsaou
