### ISSUE TITLE
PostgreSQL error

### ISSUE THREAD

**Issue by JurajMlich** [firehol/netdata#4097]
Hello, I'm unable to get postgresql monitoring enabled. Seems  I have everything set correctly, but still receiving this error:

`jurajmlich@rs-01 ~ 1$ sudo /usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin debug trace 1 postgres
2018-08-31 01:08:51:  INFO: Using python v2
2018-08-31 01:08:51:  INFO: YAML output is ordered
2018-08-31 01:08:51: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2018-08-31 01:08:51: python.d INFO: MODULES_DIR='/usr/lib/x86_64-linux-gnu/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['postgres']
2018-08-31 01:08:51: python.d DEBUG: postgres: loading module configuration: '/etc/netdata/python.d/postgres.conf'
2018-08-31 01:08:51: python.d DEBUG: postgres: reading configuration
2018-08-31 01:08:51: python.d DEBUG: postgres/socket: job added
2018-08-31 01:08:51: python.d DEBUG: all job objects [<Service(socket, initial daemon)>]
2018-08-31 01:08:51: python.d INFO: CHECKED OK: postgres_socket
2018-08-31 01:08:51: python.d INFO: RENAMED: postgres_local , from postgres_socket
2018-08-31 01:08:51: python.d DEBUG: overridden job names: ['postgres_local']
2018-08-31 01:08:51: python.d DEBUG: all remaining job objects: [<Service(local, initial daemon)>]
2018-08-31 01:08:51: python.d DEBUG: postgres_local failed to receive data during create().
2018-08-31 01:08:51: python.d ERROR: postgres_local create function failed.
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin", line 542, in run
    TRACE_FLAG = conf['trace']
KeyError: 'trace'
2018-08-31 01:08:51: python.d ERROR: DISABLED: postgres/local
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin", line 542, in run
    TRACE_FLAG = conf['trace']
KeyError: 'trace'
2018-08-31 01:08:51: python.d FATAL: no more jobs
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin", line 542, in run
    TRACE_FLAG = conf['trace']
KeyError: 'trace'
DISABLE
`

If a set incorrect password `/etc/netdata/python.d/postgres.conf `, I get correct error telling me that my credentials are wrong. Any hint in which way I should proceed? Thanks

**Comment by roedie** [comment]
Can you show your postgres.conf?

**Comment by roedie** [comment]
Oh, no, I meant the netdata postgres.conf

**Comment by JurajMlich** [comment]
Here it is
```
socket:
    name     : 'local'
    user     : 'postgres'
    database : 'postgres'

tcp:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : 'localhost'
    port     : 5432
    password : 'mypassword'

tcpipv4:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : '127.0.0.1'
    port     : 5432

tcpipv6:
    name     : 'local'
    database : 'postgres'
    user     : 'postgres'
    host     : '::1'
    port     : 5432

```

**Comment by ktsaou** [comment]
@l2isbad @facetoe @anayrat  please have a look at this.

**Comment by JurajMlich** [comment]
Without trace, the output would be:

```
sudo /usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin debug 1 postgres
2018-09-07 07:00:35:  INFO: Using python v2
2018-09-07 07:00:35:  INFO: YAML output is ordered
2018-09-07 07:00:35: python.d INFO: reading configuration file: /etc/netdata/python.d.conf
2018-09-07 07:00:35: python.d INFO: MODULES_DIR='/usr/lib/x86_64-linux-gnu/netdata/python.d/', CONFIG_DIR='/etc/netdata/', UPDATE_EVERY=1, ONLY_MODULES=['postgres']
2018-09-07 07:00:35: python.d DEBUG: postgres: loading module configuration: '/etc/netdata/python.d/postgres.conf'
2018-09-07 07:00:35: python.d DEBUG: postgres: reading configuration
2018-09-07 07:00:35: python.d DEBUG: postgres/tcp: job added
2018-09-07 07:00:35: python.d DEBUG: all job objects [<Service(tcp, initial daemon)>]
2018-09-07 07:00:35: python.d INFO: CHECKED OK: postgres_tcp
2018-09-07 07:00:35: python.d INFO: RENAMED: postgres_local , from postgres_tcp
2018-09-07 07:00:35: python.d DEBUG: overridden job names: ['postgres_local']
2018-09-07 07:00:35: python.d DEBUG: all remaining job objects: [<Service(local, initial daemon)>]
2018-09-07 07:00:35: python.d DEBUG: postgres_local failed to receive data during create().
2018-09-07 07:00:35: python.d ERROR: postgres_local create function failed.
2018-09-07 07:00:35: python.d ERROR: DISABLED: postgres/local
2018-09-07 07:00:35: python.d FATAL: no more jobs
DISABLE

```

**Comment by JurajMlich** [comment]
```
jurajmlich@rs-01 ~ 1$ netdata -v
netdata 1.6.0
```

**Comment by anayrat** [comment]
Hi,
Could you provide postgres logs?

**Comment by JurajMlich** [comment]
This is generated after running the debug command in the comments above. I'm running PostgreSQL 10.5 (Debian 10.5-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

May the problem be here? That I'm using PostgreSQL 10.5?

```
2018-09-07 10:42:09.775 CEST [2545] postgres@postgres ERROR:  could not open directory "pg_xlog/archive_status": No such file or directory
2018-09-07 10:42:09.775 CEST [2545] postgres@postgres STATEMENT:  
	SELECT
	    CAST(COUNT(*) AS INT) AS file_count,
	    CAST(COALESCE(SUM(CAST(archive_file ~ $r$\.ready$$r$ as INT)), 0) AS INT) AS ready_count,
	    CAST(COALESCE(SUM(CAST(archive_file ~ $r$\.done$$r$ AS INT)), 0) AS INT) AS done_count
	FROM
	    pg_catalog.pg_ls_dir('pg_xlog/archive_status') AS archive_files (archive_file);
```

**Comment by anayrat** [comment]
Yes it is a bug in the query, we should change "pg_xlog/archive_status" to "pg_wal/archive_status".
